QBShared = QBShared or {}
QBShared.VehicleHashes = {}

QBShared.Vehicles = {
	-- Compacts
	['blista'] = {
		['name'] = 'Blista',
		['brand'] = 'Dinka',
		['model'] = 'blista',
		['price'] = 18000,
		['class'] = 'a',
		['category'] = 'compacts',
		['hash'] = `blista`,
		['shop'] = 'pdm',
	},
	['dilettante'] = {
		['name'] = 'Dilettante',
		['brand'] = 'Karin',
		['model'] = 'dilettante',
		['price'] = 22000,
		['class'] = 'd',
		['category'] = 'compacts',
		['hash'] = `dilettante`,
		['shop'] = 'pdm',
	},
	['issi2'] = {
		['name'] = 'Issi',
		['brand'] = 'Weeny',
		['model'] = 'issi2',
		['price'] = 10000,
		['class'] = 'b',
		['category'] = 'compacts',
		['hash'] = `issi2`,
		['shop'] = 'pdm',
	},
	['prairie'] = {
		['name'] = 'Prairie',
		['brand'] = 'Bollokan',
		['model'] = 'prairie',
		['price'] = 8640,
		['class'] = 'c',
		['category'] = 'compacts',
		['hash'] = `prairie`,
		['shop'] = 'pdm',
	},
	['panto'] = {
		['name'] = 'Panto',
		['brand'] = 'Benefactor',
		['model'] = 'panto',
		['price'] = 12960,
		['class'] = 'c',
		['category'] = 'compacts',
		['hash'] = `panto`,
		['shop'] = 'pdm',
	},
	['club'] = {
		['name'] = 'Club',
		['brand'] = 'BF',
		['model'] = 'club',
		['price'] = 9180,
		['class'] = 'c',
		['category'] = 'compacts',
		['hash'] = `club`,
		['shop'] = 'pdm',
	},
	['weevil'] = {
		['name'] = 'Weevil',
		['brand'] = 'BF',
		['model'] = 'weevil',
		['price'] = 5400,
		['class'] = 'd',
		['category'] = 'compacts',
		['hash'] = `weevil`,
		['shop'] = 'pdm',
	},
	['brioso3'] = {
		['name'] = 'Brioso 300 Widebody',
		['brand'] = 'Benefactor',
		['model'] = 'brioso3',
		['price'] = 6515,
		['class'] = 'c',
		['category'] = 'compacts',
		['hash'] = `brioso3`,
		['shop'] = 'pdm',
	},
	-- Sedans
	['asea'] = {
		['name'] = 'Asea',
		['brand'] = 'Declasse',
		['model'] = 'asea',
		['price'] = 9180,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `asea`,
		['shop'] = 'pdm',
	},
	['asterope'] = {
		['name'] = 'Asterope',
		['brand'] = 'Karin',
		['model'] = 'asterope',
		['price'] = 44280,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `asterope`,
		['shop'] = 'pdm',
	},
	['glendale'] = {
		['name'] = 'Glendale',
		['brand'] = 'Benefactor',
		['model'] = 'glendale',
		['price'] = 9072,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `glendale`,
		['shop'] = 'pdm',
	},
	['fugitive'] = {
		['name'] = 'Fugitive',
		['brand'] = 'Cheval',
		['model'] = 'fugitive',
		['price'] = 37800,
		['class'] = 'b',
		['category'] = 'sedans',
		['hash'] = `fugitive`,
		['shop'] = 'pdm',
	},
	['ingot'] = {
		['name'] = 'Ingot',
		['brand'] = 'Vulcar',
		['model'] = 'ingot',
		['price'] = 6804,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `ingot`,
		['shop'] = 'pdm',
	},
	['intruder'] = {
		['name'] = 'Intruder',
		['brand'] = 'Vulcar',
		['model'] = 'intruder',
		['price'] = 18360,
		['class'] = 'b',
		['category'] = 'sedans',
		['hash'] = `intruder`,
		['shop'] = 'pdm',
	},
	['surge'] = {
		['name'] = 'Surge',
		['brand'] = 'Vulcar',
		['model'] = 'surge',
		['price'] = 21600,
		['class'] = 'd',
		['category'] = 'sedans',
		['hash'] = `surge`,
		['shop'] = 'pdm',
	},
	['stretch'] = {
		['name'] = 'Stretch',
		['brand'] = 'Dundreary',
		['model'] = 'stretch',
		['price'] = 324000,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `stretch`,
		['shop'] = 'pdm',
	},
	['premier'] = {
		['name'] = 'Premier',
		['brand'] = 'Declasse',
		['model'] = 'premier',
		['price'] = 135000,
		['class'] = 'a',
		['category'] = 'sedans',
		['hash'] = `premier`,
		['shop'] = 'pdm',
	},
	['regina'] = {
		['name'] = 'Regina',
		['brand'] = 'Dundreary',
		['model'] = 'regina',
		['price'] = 11880,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `regina`,
		['shop'] = 'pdm',
	},
	['schafter'] = {
		['name'] = 'Schafter',
		['brand'] = 'Benefactor',
		['model'] = 'schafter',
		['price'] = 157000,
		['class'] = 'b',
		['category'] = 'sedans',
		['hash'] = `schafter`,
		['shop'] = 'empty',
	},
	['superd'] = {
		['name'] = 'Super Diamond',
		['brand'] = 'Enus',
		['model'] = 'superd',
		['price'] = 356400,
		['class'] = 'b',
		['category'] = 'sedans',
		['hash'] = `superd`,
		['shop'] = 'pdm',
	},
	['tailgater'] = {
		['name'] = 'Tailgater',
		['brand'] = 'Obey',
		['model'] = 'tailgater',
		['price'] = 52460,
		['class'] = 'a',
		['category'] = 'sedans',
		['hash'] = `tailgater`,
		['shop'] = 'pdm',
	},
	['washington'] = {
		['name'] = 'Washington',
		['brand'] = 'Albany',
		['model'] = 'washington',
		['price'] = 21600,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `washington`,
		['shop'] = 'pdm',
	},
	['warrener'] = {
		['name'] = 'Warrener',
		['brand'] = 'Vulcar',
		['model'] = 'warrener',
		['price'] = 20000,
		['class'] = 'b',
		['category'] = 'sedans',
		['hash'] = `warrener`,
		['shop'] = 'pdm',
	},
	['cinquemila'] = {
		['name'] = 'Cinquemila',
		['brand'] = 'Lampadati',
		['model'] = 'cinquemila',
		['price'] = 80576,
		['class'] = 'b',
		['category'] = 'sedans',
		['hash'] = `cinquemila`,
		['shop'] = 'pdm',
	},
	['deity'] = {
		['name'] = 'Deity',
		['brand'] = 'Enus',
		['model'] = 'deity',
		['price'] = 137600,
		['class'] = 'b',
		['category'] = 'sedans',
		['hash'] = `deity`,
		['shop'] = 'pdm',
	},
	['tailgater2'] = {
		['name'] = 'Tailgater S',
		['brand'] = 'Obey',
		['model'] = 'tailgater2',
		['price'] = 837160,
		['class'] = 's',
		['category'] = 'sedans',
		['hash'] = `tailgater2`,
		['shop'] = 'pdm',
	},
	-- SUVs
	['gresley'] = {
		['name'] = 'Gresley',
		['brand'] = 'Bravado',
		['model'] = 'gresley',
		['price'] = 21600,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `gresley`,
		['shop'] = 'pdm',
	},
	['cavalcade'] = {
		['name'] = 'Cavalcade',
		['brand'] = 'Albany',
		['model'] = 'cavalcade',
		['price'] = 22680,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `cavalcade`,
		['shop'] = 'pdm',
	},
	['cavalcade2'] = {
		['name'] = 'Cavalcade',
		['brand'] = 'Albany',
		['model'] = 'cavalcade2',
		['price'] = 17474,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `cavalcade2`,
		['shop'] = 'pdm',
	},
	['bjxl'] = {
		['name'] = 'BeeJay XL',
		['brand'] = 'Karin',
		['model'] = 'bjxl',
		['price'] = 41040,
		['class'] = 'd',
		['category'] = 'suvs',
		['hash'] = `bjxl`,
		['shop'] = 'empty',
	},
	['baller'] = {
		['name'] = 'Baller',
		['brand'] = 'Gallivanter',
		['model'] = 'baller',
		['price'] = 43200,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `baller`,
		['shop'] = 'pdm',
	},
	['baller2'] = {
		['name'] = 'Baller',
		['brand'] = 'Gallivanter',
		['model'] = 'baller2',
		['price'] = 48600,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `baller2`,
		['shop'] = 'pdm',
	},
	['seminole'] = {
		['name'] = 'Seminole',
		['brand'] = 'Canis',
		['model'] = 'seminole',
		['price'] = 6804,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `seminole`,
		['shop'] = 'pdm',
	},
	['fq2'] = {
		['name'] = 'FQ 2',
		['brand'] = 'Fathom',
		['model'] = 'fq2',
		['price'] = 31320,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `fq2`,
		['shop'] = 'pdm',
	},
	['habanero'] = {
		['name'] = 'Habanero',
		['brand'] = 'Emperor',
		['model'] = 'habanero',
		['price'] = 11880,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `habanero`,
		['shop'] = 'pdm',
	},
	['granger'] = {
		['name'] = 'Granger',
		['brand'] = 'Declasse',
		['model'] = 'granger',
		['price'] = 23760,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `granger`,
		['shop'] = 'pdm',
	},
	['landstalker'] = {
		['name'] = 'Landstalker',
		['brand'] = 'Dundreary',
		['model'] = 'landstalker',
		['price'] = 54000,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `landstalker`,
		['shop'] = 'pdm',
	},
	['mesa'] = {
		['name'] = 'Mesa',
		['brand'] = 'Canis',
		['model'] = 'mesa',
		['price'] = 18900,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `mesa`,
		['shop'] = 'pdm',
	},
	['patriot'] = {
		['name'] = 'Patriot',
		['brand'] = 'Mammoth',
		['model'] = 'patriot',
		['price'] = 32400,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `patriot`,
		['shop'] = 'pdm',
	},
	['rocoto'] = {
		['name'] = 'Rocoto',
		['brand'] = 'Obey',
		['model'] = 'rocoto',
		['price'] = 120400,
		['class'] = 'a',
		['category'] = 'suvs',
		['hash'] = `rocoto`,
		['shop'] = 'pdm',
	},
	['jubilee'] = {
		['name'] = 'Jubilee',
		['brand'] = 'Enus',
		['model'] = 'jubilee',
		['price'] = 351000,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `jubilee`,
		['shop'] = 'pdm',
	},
	['huntley'] = {
		['name'] = 'Huntley S',
		['brand'] = 'Enus',
		['model'] = 'huntley',
		['price'] = 216000,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `huntley`,
		['shop'] = 'pdm',
	},
	['squaddie'] = {
		['name'] = 'squaddie',
		['brand'] = 'Mammoth',
		['model'] = 'squaddie',
		['price'] = 108000,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `squaddie`,
		['shop'] = 'empty',
	},
	['astron'] = {
		['name'] = 'Astron',
		['brand'] = 'Pfister',
		['model'] = 'astron',
		['price'] = 67554,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `astron`,
		['shop'] = 'pdm',
	},
	['issi8'] = {
		['name'] = 'Issi Rally',
		['brand'] = 'Weeny',
		['model'] = 'issi8',
		['price'] = 32400,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `issi8`,
		['shop'] = 'pdm',
	},
-- Coupes
	['felon2'] = {
		['name'] = 'Felon GT',
		['brand'] = 'Weeny',
		['model'] = 'felon2',
		['price'] = 17000,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `felon2`,
		['shop'] = 'pdm',
	},
	['exemplar'] = {
		['name'] = 'Exemplar',
		['brand'] = 'Dewbauchee',
		['model'] = 'exemplar',
		['price'] = 60000,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `exemplar`,
		['shop'] = 'pdm',
	},
	['f620'] = {
		['name'] = 'F620',
		['brand'] = 'Obey',
		['model'] = 'f620',
		['price'] = 29700,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `f620`,
		['shop'] = 'pdm',
	},
	['felon'] = {
		['name'] = 'Felon',
		['brand'] = 'Lampadati',
		['model'] = 'felon',
		['price'] = 27000,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `felon`,
		['shop'] = 'pdm',
	},
	['oracle'] = {
		['name'] = 'Oracle XS',
		['brand'] = 'Ubermacht',
		['model'] = 'oracle',
		['price'] = 21600,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `oracle`,
		['shop'] = 'pdm',
	},
	['sentinel'] = {
		['name'] = 'Sentinel XS',
		['brand'] = 'Ubermacht',
		['model'] = 'sentinel',
		['price'] = 86400,
		['class'] = 'a',
		['category'] = 'coupes',
		['hash'] = `sentinel`,
		['shop'] = 'pdm',
	},
	['windsor'] = {
		['name'] = 'Windsor',
		['brand'] = 'Enus',
		['model'] = 'windsor',
		['price'] = 378000,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `windsor`,
		['shop'] = 'pdm',
	},
-- Muscle
	['buccaneer'] = {
		['name'] = 'Buccaneer',
		['brand'] = 'Albany',
		['model'] = 'buccaneer',
		['price'] = 12960,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `buccaneer`,
		['shop'] = 'pdm',
	},
	['vigero2'] = {
		['name'] = 'Vigero ZX',
		['brand'] = 'Declasse',
		['model'] = 'vigero2',
		['price'] = 110975,
		['class'] = 'a',
		['category'] = 'muscle',
		['hash'] = `vigero2`,
		['shop'] = 'pdm',
	},
	['dominator'] = {
		['name'] = 'Dominator',
		['brand'] = 'Vapid',
		['model'] = 'dominator',
		['price'] = 116400,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `dominator`,
		['shop'] = 'pdm',
	},
	['gauntlet'] = {
		['name'] = 'Gauntlet',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet',
		['price'] = 132453,
		['class'] = 's',
		['category'] = 'muscle',
		['hash'] = `gauntlet`,
		['shop'] = 'pdm',
	},
	['phoenix'] = {
		['name'] = 'Phoenix',
		['brand'] = 'Imponte',
		['model'] = 'phoenix',
		['price'] = 23760,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `phoenix`,
		['shop'] = 'pdm',
	},
	['ruiner'] = {
		['name'] = 'Ruiner',
		['brand'] = 'Imponte',
		['model'] = 'ruiner',
		['price'] = 23760,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `ruiner`,
		['shop'] = 'pdm',
	},
	['voodoo2'] = {
		['name'] = 'Voodoo',
		['brand'] = 'Declasse',
		['model'] = 'voodoo2',
		['price'] = 43200,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `voodoo2`,
		['shop'] = 'pdm',
	},
	['chino'] = {
		['name'] = 'Chino',
		['brand'] = 'Vapid',
		['model'] = 'chino',
		['price'] = 21600,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `chino`,
		['shop'] = 'pdm',
	},
	['yosemite'] = {
		['name'] = 'Yosemite',
		['brand'] = 'Declasse',
		['model'] = 'yosemite',
		['price'] = 21600,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `yosemite`,
		['shop'] = 'pdm',
	},
	['virgo'] = {
		['name'] = 'Virgo',
		['brand'] = 'Albany',
		['model'] = 'virgo',
		['price'] = 23760,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `virgo`,
		['shop'] = 'pdm',
	},
	['peyote2'] = {
		['name'] = 'Peyote Gasser',
		['brand'] = 'Vapid',
		['model'] = 'peyote2',
		['price'] = 30240,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `peyote2`,
		['shop'] = 'pdm',
	},
	['buffalo4'] = {
		['name'] = 'Buffalo STX',
		['brand'] = 'Bravado',
		['model'] = 'buffalo4',
		['price'] = 140800,
		['class'] = 's',
		['category'] = 'muscle',
		['hash'] = `buffalo4`,
		['shop'] = 'pdm',
	},
	['dukes'] = {
		['name'] = 'Dukes',
		['brand'] = 'Imponte',
		['model'] = 'dukes',
		['price'] = 19440,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `dukes`,
		['shop'] = 'pdm',
	},
	['sabregt'] = {
		['name'] = 'Sabre Turbo',
		['brand'] = 'Declasse',
		['model'] = 'sabregt',
		['price'] = 19440,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `sabregt`,
		['shop'] = 'pdm',
	},
-- SportsClassics
	['manana'] = {
		['name'] = 'Manana',
		['brand'] = 'Albany',
		['model'] = 'manana',
		['price'] = 43200,
		['class'] = 'c',
		['category'] = 'SportsClassics',
		['hash'] = `manana`,
		['shop'] = 'pdm',
	},
	['tornado'] = {
		['name'] = 'Tornado',
		['brand'] = 'Declasse',
		['model'] = 'tornado',
		['price'] = 43200,
		['class'] = 'c',
		['category'] = 'SportsClassics',
		['hash'] = `tornado`,
		['shop'] = 'pdm',
	},
	['ztype'] = {
		['name'] = 'Z-Type',
		['brand'] = 'Truffade',
		['model'] = 'ztype',
		['price'] = 600000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `ztype`,
		['shop'] = 'pdm',
	},
	['monroe'] = {
		['name'] = 'Monroe',
		['brand'] = 'Pegassi',
		['model'] = 'monroe',
		['price'] = 145000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `monroe`,
		['shop'] = 'pdm',
	},
	['stinger'] = {
		['name'] = 'Stinger',
		['brand'] = 'Grotti',
		['model'] = 'stinger',
		['price'] = 256000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `stinger`,
		['shop'] = 'pdm',
	},
	['tornado6'] = {
		['name'] = 'Tornado Rat Rod',
		['brand'] = 'Declasse',
		['model'] = 'tornado6',
		['price'] = 64800,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `tornado6`,
		['shop'] = 'pdm',
	},
	['infernus2'] = {
		['name'] = 'Infernus Classic',
		['brand'] = 'Pegassi',
		['model'] = 'infernus2',
		['price'] = 324000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `infernus2`,
		['shop'] = 'pdm',
	},
	['ardent'] = {
		['name'] = 'Ardent',
		['brand'] = 'Ocelot',
		['model'] = 'ardent',
		['price'] = 19120,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `ardent`,
		['shop'] = 'pdm',
	},
-- SportsClassics
	['ninef'] = {
		['name'] = '9F',
		['brand'] = 'Obey',
		['model'] = 'ninef',
		['price'] = 694668,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `ninef`,
		['shop'] = 'pdm',
	},
	['buffalo2'] = {
		['name'] = 'Buffalo S',
		['brand'] = 'Bravado',
		['model'] = 'buffalo2',
		['price'] = 27000,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `buffalo2`,
		['shop'] = 'pdm',
	},
	['ninef2'] = {
		['name'] = '9F Cabrio',
		['brand'] = 'Obey',
		['model'] = 'ninef2',
		['price'] = 65000,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `ninef2`,
		['shop'] = 'pdm',
	},
	['jester'] = {
		['name'] = 'Jester',
		['brand'] = 'Dinka',
		['model'] = 'jester',
		['price'] = 145800,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `jester`,
		['shop'] = 'pdm',
	},
	['buffalo'] = {
		['name'] = 'Buffalo',
		['brand'] = 'Bravado',
		['model'] = 'buffalo',
		['price'] = 37800,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `buffalo`,
		['shop'] = 'pdm',
	},
	['massacro'] = {
		['name'] = 'Massacro',
		['brand'] = 'Dewbauchee',
		['model'] = 'massacro',
		['price'] = 113131,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `massacro`,
		['shop'] = 'pdm',
	},
	['comet2'] = {
		['name'] = 'Comet',
		['brand'] = 'Pfister',
		['model'] = 'comet2',
		['price'] = 280000,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `comet2`,
		['shop'] = 'pdm',
	},
	['omnisegt'] = {
		['name'] = 'Omnis e-GT',
		['brand'] = 'Obey',
		['model'] = 'omnisegt',
		['price'] = 140600,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `omnisegt`,
		['shop'] = 'pdm',
	},
	['carbonizzare'] = {
		['name'] = 'Carbonizzare',
		['brand'] = 'Grotti',
		['model'] = 'carbonizzare',
		['price'] = 75000,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `carbonizzare`,
		['shop'] = 'pdm',
	},
	['elegy2'] = {
		['name'] = 'Elegy RH8',
		['brand'] = 'Annis',
		['model'] = 'elegy2',
		['price'] = 833126,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `elegy2`,
		['shop'] = 'pdm',
	},
	['feltzer2'] = {
		['name'] = 'Feltzer',
		['brand'] = 'Benefactor',
		['model'] = 'feltzer2',
		['price'] = 1381960,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `feltzer2`,
		['shop'] = 'pdm',
	},
	['khamelion'] = {
		['name'] = 'Khamelion',
		['brand'] = 'Hijak',
		['model'] = 'khamelion',
		['price'] = 129600,
		['class'] = 'c',
		['category'] = 'Sports',
		['hash'] = `khamelion`,
		['shop'] = 'pdm',
	},
	['raiden'] = {
		['name'] = 'Raiden',
		['brand'] = 'Coil',
		['model'] = 'raiden',
		['price'] = 50000,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `raiden`,
		['shop'] = 'pdm',
	},
	['penumbra'] = {
		['name'] = 'Penumbra',
		['brand'] = 'Maibatsu',
		['model'] = 'penumbra',
		['price'] = 163567,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `penumbra`,
		['shop'] = 'pdm',
	},
	['rapidgt'] = {
		['name'] = 'Rapid',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt',
		['price'] = 95000,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `rapidgt`,
		['shop'] = 'pdm',
	},
	['rapidgt2'] = {
		['name'] = 'Rapid GT',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt2',
		['price'] = 75600,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `rapidgt2`,
		['shop'] = 'pdm',
	},
	['alpha'] = {
		['name'] = 'Alpha',
		['brand'] = 'Albany',
		['model'] = 'alpha',
		['price'] = 29000,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `alpha`,
		['shop'] = 'pdm',
	},
	['schwarzer'] = {
		['name'] = 'Schwartzer',
		['brand'] = 'Benefactor',
		['model'] = 'schwarzer',
		['price'] = 121800,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `schwarzer`,
		['shop'] = 'pdm',
	},
	['sultan'] = {
		['name'] = 'Sultan',
		['brand'] = 'Karin',
		['model'] = 'sultan',
		['price'] = 118569,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `sultan`,
		['shop'] = 'pdm',
	},
	['surano'] = {
		['name'] = 'Surano',
		['brand'] = 'Benefactor',
		['model'] = 'surano',
		['price'] = 108000,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `surano`,
		['shop'] = 'pdm',
	},
	['sultan3'] = {
		['name'] = 'Sultan RS Classic',
		['brand'] = 'Karin',
		['model'] = 'sultan3',
		['price'] = 130177,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `sultan3`,
		['shop'] = 'pdm',
	},
	['comet6'] = {
		['name'] = 'Comet S2',
		['brand'] = 'Pfister',
		['model'] = 'comet6',
		['price'] = 500000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `comet6`,
		['shop'] = 'pdm',
	},
	['furoregt'] = {
		['name'] = 'Furore GT',
		['brand'] = 'Lampadati',
		['model'] = 'furoregt',
		['price'] = 495000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `furoregt`,
		['shop'] = 'pdm',
	},
	['penumbra2'] = {
		['name'] = 'Penumbra FF',
		['brand'] = 'Maibatsu',
		['model'] = 'penumbra2',
		['price'] = 134428,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `penumbra2`,
		['shop'] = 'pdm',
	},
	['neon'] = {
		['name'] = 'Neon',
		['brand'] = 'Pfister',
		['model'] = 'neon',
		['price'] = 162000,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `neon`,
		['shop'] = 'pdm',
	},
	['blista2'] = {
		['name'] = 'Blista Compact',
		['brand'] = 'Dinka',
		['model'] = 'blista2',
		['price'] = 8640,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `blista2`,
		['shop'] = 'pdm',
	},
	['jugular'] = {
		['name'] = 'Jugular',
		['brand'] = 'Ocelot',
		['model'] = 'jugular',
		['price'] = 154283,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `jugular`,
		['shop'] = 'pdm',
	},
	['imorgon'] = {
		['name'] = 'Imorgon',
		['brand'] = 'Overflod',
		['model'] = 'imorgon',
		['price'] = 416000,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `imorgon`,
		['shop'] = 'pdm',
	},
	['coquette4'] = {
		['name'] = 'Coquette D10',
		['brand'] = 'Invetero',
		['model'] = 'coquette4',
		['price'] = 370000,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `coquette4`,
		['shop'] = 'pdm',
	},
	['italirsx'] = {
		['name'] = 'Itali RSX',
		['brand'] = 'Grotti',
		['model'] = 'italirsx',
		['price'] = 765752,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `italirsx`,
		['shop'] = 'pdm',
	},
	['growler'] = {
		['name'] = 'Growler',
		['brand'] = 'Pfister',
		['model'] = 'growler',
		['price'] = 161992,
		['class'] = 'a',
		['category'] = 'Sports',
		['hash'] = `growler`,
		['shop'] = 'pdm',
	},
	['futo'] = {
		['name'] = 'Futo',
		['brand'] = 'Karin',
		['model'] = 'futo',
		['price'] = 20264,
		['class'] = 'b',
		['category'] = 'Sports',
		['hash'] = `futo`,
		['shop'] = 'pdm',
	},
-- super
	['bullet'] = {
		['name'] = 'Bullet',
		['brand'] = 'Karin',
		['model'] = 'bullet',
		['price'] = 162000,
		['class'] = 'a',
		['category'] = 'super',
		['hash'] = `bullet`,
		['shop'] = 'pdm',
	},
	['voltic'] = {
		['name'] = 'Voltic',
		['brand'] = 'Coil',
		['model'] = 'voltic',
		['price'] = 194400,
		['class'] = 'b',
		['category'] = 'super',
		['hash'] = `voltic`,
		['shop'] = 'pdm',
	},
	['zentorno'] = {
		['name'] = 'Zentorno',
		['brand'] = 'Pegassi',
		['model'] = 'zentorno',
		['price'] = 726000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `zentorno`,
		['shop'] = 'pdm',
	},
	['cheetah'] = {
		['name'] = 'Cheetah',
		['brand'] = 'Grotti',
		['model'] = 'cheetah',
		['price'] = 702000,
		['class'] = 'a',
		['category'] = 'super',
		['hash'] = `cheetah`,
		['shop'] = 'pdm',
	},
	['entityxf'] = {
		['name'] = 'Entity XF',
		['brand'] = 'Overflod',
		['model'] = 'entityxf',
		['price'] = 756000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `entityxf`,
		['shop'] = 'pdm',
	},
	['adder'] = {
		['name'] = 'Adder',
		['brand'] = 'Truffade',
		['model'] = 'adder',
		['price'] = 1350000,
		['class'] = 'a',
		['category'] = 'super',
		['hash'] = `adder`,
		['shop'] = 'pdm',
	},
	['infernus'] = {
		['name'] = 'Infernus',
		['brand'] = 'Pegassi',
		['model'] = 'infernus',
		['price'] = 259200,
		['class'] = 'a',
		['category'] = 'super',
		['hash'] = `infernus`,
		['shop'] = 'pdm',
	},
	['vacca'] = {
		['name'] = 'Vacca',
		['brand'] = 'Pegassi',
		['model'] = 'vacca',
		['price'] = 1367829,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `vacca`,
		['shop'] = 'pdm',
	},
	['osiris'] = {
		['name'] = 'Osiris',
		['brand'] = 'Pegassi',
		['model'] = 'osiris',
		['price'] = 880000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `osiris`,
		['shop'] = 'pdm',
	},
	['champion'] = {
		['name'] = 'Champion',
		['brand'] = 'Dewbauchee',
		['model'] = 'champion',
		['price'] = 1531505,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `champion`,
		['shop'] = 'pdm',
	},
	['krieger'] = {
		['name'] = 'Krieger',
		['brand'] = 'Benefactor',
		['model'] = 'krieger',
		['price'] = 1530000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `krieger`,
		['shop'] = 'pdm',
	},
	['fmj'] = {
		['name'] = 'FMJ',
		['brand'] = 'Vapid',
		['model'] = 'fmj',
		['price'] = 540000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `fmj`,
		['shop'] = 'pdm',
	},
	['italigtb'] = {
		['name'] = 'Itali GTB',
		['brand'] = 'Progen',
		['model'] = 'italigtb',
		['price'] = 522267,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `italigtb`,
		['shop'] = 'pdm',
	},
	['emerus'] = {
		['name'] = 'Emerus',
		['brand'] = 'Progen',
		['model'] = 'emerus',
		['price'] = 2800000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `emerus`,
		['shop'] = 'pdm',
	},
	['furia'] = {
		['name'] = 'Furia',
		['brand'] = 'Grotti',
		['model'] = 'furia',
		['price'] = 640000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `furia`,
		['shop'] = 'pdm',
	},
	['ignus'] = {
		['name'] = 'Ignus',
		['brand'] = 'Pegassi',
		['model'] = 'ignus',
		['price'] = 935000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `ignus`,
		['shop'] = 'pdm',
	},
-- vans
	['boxville2'] = {
		['name'] = 'Boxville ',
		['brand'] = 'Brute',
		['model'] = 'boxville2',
		['price'] = 8505,
		['class'] = 'd',
		['category'] = 'Vans',
		['hash'] = `boxville2`,
		['shop'] = 'empty',
	},
	['pony'] = {
		['name'] = 'Pony ',
		['brand'] = 'Brute',
		['model'] = 'pony',
		['price'] = 15120,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `pony`,
		['shop'] = 'pdm',
	},
	['bison'] = {
		['name'] = 'Bison',
		['brand'] = 'Bravado',
		['model'] = 'bison',
		['price'] = 25380,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `bison`,
		['shop'] = 'pdm',
	},
	['bison'] = {
		['name'] = 'Bison',
		['brand'] = 'Bravado',
		['model'] = 'bison',
		['price'] = 25380,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `bison`,
		['shop'] = 'pdm',
	},
	['bobcatxl'] = {
		['name'] = 'Bobcat XL',
		['brand'] = 'Vapid',
		['model'] = 'bobcatxl',
		['price'] = 5400,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `bobcatxl`,
		['shop'] = 'pdm',
	},
	['burrito'] = {
		['name'] = 'Burrito',
		['brand'] = 'Declasse',
		['model'] = 'burrito',
		['price'] = 12960,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `burrito`,
		['shop'] = 'pdm',
	},
	['burrito2'] = {
		['name'] = 'Burrito',
		['brand'] = 'Declasse',
		['model'] = 'burrito2',
		['price'] = 12960,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `burrito2`,
		['shop'] = 'empty',
	},
	['minivan'] = {
		['name'] = 'Minivan',
		['brand'] = 'Vapid',
		['model'] = 'minivan',
		['price'] = 10800,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `minivan`,
		['shop'] = 'pdm',
	},
	['taxi'] = {
		['name'] = 'Taxi',
		['brand'] = 'Vapid',
		['model'] = 'taxi',
		['price'] = 10800,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `taxi`,
		['shop'] = 'pdm',
	},
	['speedo'] = {
		['name'] = 'Speedo',
		['brand'] = 'Vapid',
		['model'] = 'speedo',
		['price'] = 20644,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `speedo`,
		['shop'] = 'empty',
	},
	['surfer'] = {
		['name'] = 'Surfer',
		['brand'] = 'BF',
		['model'] = 'surfer',
		['price'] = 10800,
		['class'] = 'd',
		['category'] = 'Vans',
		['hash'] = `surfer`,
		['shop'] = 'pdm',
	},
	['taco'] = {
		['name'] = 'Taco Van',
		['brand'] = 'Brute',
		['model'] = 'taco',
		['price'] = 10800,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `taco`,
		['shop'] = 'empty',
	},
	['paradise'] = {
		['name'] = 'Paradise',
		['brand'] = 'Bravado',
		['model'] = 'paradise',
		['price'] = 16200,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `paradise`,
		['shop'] = 'pdm',
	},
	['youga3'] = {
		['name'] = 'Youga Classic 4x4',
		['brand'] = 'Bravado',
		['model'] = 'youga3',
		['price'] = 8100,
		['class'] = 'd',
		['category'] = 'Vans',
		['hash'] = `youga3`,
		['shop'] = 'pdm',
	},
	['rumpo3'] = {
		['name'] = 'Rumpo Custom',
		['brand'] = 'Bravado',
		['model'] = 'rumpo3',
		['price'] = 54000,
		['class'] = 'c',
		['category'] = 'Vans',
		['hash'] = `rumpo3`,
		['shop'] = 'pdm',
	},
-- Motorcycles
	['bati'] = {
		['name'] = 'Bati 801',
		['brand'] = 'Pegassi',
		['model'] = 'bati',
		['price'] = 220319,
		['class'] = 's',
		['category'] = 'Motorcycles',
		['hash'] = `bati`,
		['shop'] = 'pdm',
	},
	['innovation'] = {
		['name'] = 'Innovation',
		['brand'] = 'LCC',
		['model'] = 'innovation',
		['price'] = 42120,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `innovation`,
		['shop'] = 'pdm',
	},
	['hexer'] = {
		['name'] = 'Hexer',
		['brand'] = 'LCC',
		['model'] = 'hexer',
		['price'] = 97200,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `hexer`,
		['shop'] = 'pdm',
	},
	['ruffian'] = {
		['name'] = 'Ruffian',
		['brand'] = 'Pegassi',
		['model'] = 'ruffian',
		['price'] = 55272,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `ruffian`,
		['shop'] = 'pdm',
	},
	['thrust'] = {
		['name'] = 'Thrust',
		['brand'] = 'Dinka',
		['model'] = 'thrust',
		['price'] = 47502,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `thrust`,
		['shop'] = 'pdm',
	},
	['carbonrs'] = {
		['name'] = 'Carbon RS',
		['brand'] = 'Nagasaki',
		['model'] = 'carbonrs',
		['price'] = 85213,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `carbonrs`,
		['shop'] = 'pdm',
	},
	['sanchez'] = {
		['name'] = 'Sanchez',
		['brand'] = 'Maibatsu',
		['model'] = 'sanchez',
		['price'] = 30000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `sanchez`,
		['shop'] = 'pdm',
	},
	['manchez2'] = {
		['name'] = 'Manchez Scout',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez2',
		['price'] = 47657,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `manchez2`,
		['shop'] = 'pdm',
	},
	['akuma'] = {
		['name'] = 'Akuma',
		['brand'] = 'Dinka',
		['model'] = 'akuma',
		['price'] = 36000,
		['class'] = 's',
		['category'] = 'Motorcycles',
		['hash'] = `akuma`,
		['shop'] = 'pdm',
	},
	['pcj'] = {
		['name'] = 'PCJ 600',
		['brand'] = 'Shitzu',
		['model'] = 'pcj',
		['price'] = 27000,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `pcj`,
		['shop'] = 'pdm',
	},
	['bagger'] = {
		['name'] = 'Bagger',
		['brand'] = 'Western',
		['model'] = 'bagger',
		['price'] = 18000,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `bagger`,
		['shop'] = 'pdm',
	},
	['bati2'] = {
		['name'] = 'Bati 801RR',
		['brand'] = 'Pegassi',
		['model'] = 'bati2',
		['price'] = 200788,
		['class'] = 's',
		['category'] = 'Motorcycles',
		['hash'] = `bati2`,
		['shop'] = 'pdm',
	},
	['daemon'] = {
		['name'] = 'Daemon',
		['brand'] = 'Western',
		['model'] = 'daemon',
		['price'] = 46656,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `daemon`,
		['shop'] = 'pdm',
	},
	['double'] = {
		['name'] = 'Double-T',
		['brand'] = 'Dinka',
		['model'] = 'double',
		['price'] = 139497,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `double`,
		['shop'] = 'pdm',
	},
	['vader'] = {
		['name'] = 'Vader',
		['brand'] = 'Shitzu',
		['model'] = 'vader',
		['price'] = 22000,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `vader`,
		['shop'] = 'pdm',
	},
	['faggio2'] = {
		['name'] = 'SNR Faggio',
		['brand'] = 'Pegassi',
		['model'] = 'faggio2',
		['price'] = 8000,
		['class'] = 'c',
		['category'] = 'Motorcycles',
		['hash'] = `faggio2`,
		['shop'] = 'pdm',
	},
	['faggio3'] = {
		['name'] = 'Faggio',
		['brand'] = 'Pegassi',
		['model'] = 'faggio3',
		['price'] = 5000,
		['class'] = 'c',
		['category'] = 'Motorcycles',
		['hash'] = `faggio3`,
		['shop'] = 'pdm',
	},
	['sovereign'] = {
		['name'] = 'Sovereign',
		['brand'] = 'Western',
		['model'] = 'sovereign',
		['price'] = 74520,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `sovereign`,
		['shop'] = 'pdm',
	},
	['nemesis'] = {
		['name'] = 'Nemesis',
		['brand'] = 'Principe',
		['model'] = 'nemesis',
		['price'] = 35000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `nemesis`,
		['shop'] = 'pdm',
	},
	['hakuchou'] = {
		['name'] = 'Hakuchou',
		['brand'] = 'Shitzu',
		['model'] = 'hakuchou',
		['price'] = 154313,
		['class'] = 's',
		['category'] = 'Motorcycles',
		['hash'] = `hakuchou`,
		['shop'] = 'pdm',
	},
	['faggio'] = {
		['name'] = 'Faggio Sport',
		['brand'] = 'Pegassi',
		['model'] = 'faggio',
		['price'] = 10000,
		['class'] = 'c',
		['category'] = 'Motorcycles',
		['hash'] = `faggio`,
		['shop'] = 'pdm',
	},
	['vindicator'] = {
		['name'] = 'Vindicator',
		['brand'] = 'Dinka',
		['model'] = 'vindicator',
		['price'] = 38880,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `vindicator`,
		['shop'] = 'pdm',
	},
	['bf400'] = {
		['name'] = 'BF400',
		['brand'] = 'Nagasaki',
		['model'] = 'bf400',
		['price'] = 38000,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `bf400`,
		['shop'] = 'pdm',
	},
	['sanctus'] = {
		['name'] = 'Sanctus',
		['brand'] = 'LCC',
		['model'] = 'sanctus',
		['price'] = 48600,
		['class'] = 'b',
		['category'] = 'Motorcycles',
		['hash'] = `sanctus`,
		['shop'] = 'pdm',
	},
	['manchez'] = {
		['name'] = 'Manchez',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez',
		['price'] = 48600,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `manchez`,
		['shop'] = 'pdm',
	},
-- Off-Road
	['verus'] = {
		['name'] = 'Verus',
		['brand'] = 'Dinka',
		['model'] = 'verus',
		['price'] = 9720,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `verus`,
		['shop'] = 'pdm',
	},
	['blazer'] = {
		['name'] = 'Blazer',
		['brand'] = 'Nagasaki',
		['model'] = 'blazer',
		['price'] = 7560,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `blazer`,
		['shop'] = 'pdm',
	},
	['caracara2'] = {
		['name'] = 'Caracara 4x4',
		['brand'] = 'Vapid',
		['model'] = 'caracara2',
		['price'] = 27000,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `caracara2`,
		['shop'] = 'pdm',
	},
	['bfinjection'] = {
		['name'] = 'Injection',
		['brand'] = 'BF',
		['model'] = 'bfinjection',
		['price'] = 5400,
		['class'] = 'd',
		['category'] = 'Off-Road',
		['hash'] = `bfinjection`,
		['shop'] = 'pdm',
	},
	['dloader'] = {
		['name'] = 'Duneloader',
		['brand'] = 'Bravado',
		['model'] = 'dloader',
		['price'] = 5400,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `dloader`,
		['shop'] = 'pdm',
	},
	['draugur'] = {
		['name'] = 'Draugur',
		['brand'] = 'Declasse',
		['model'] = 'draugur',
		['price'] = 32400,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `draugur`,
		['shop'] = 'pdm',
	},
	['rebel2'] = {
		['name'] = 'Rebel',
		['brand'] = 'Karin',
		['model'] = 'rebel2',
		['price'] = 15660,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `rebel2`,
		['shop'] = 'pdm',
	},
	['sandking2'] = {
		['name'] = 'Sandking SWB',
		['brand'] = 'Vapid',
		['model'] = 'sandking2',
		['price'] = 32400,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `sandking2`,
		['shop'] = 'pdm',
	},
	['patriot3'] = {
		['name'] = 'Patriot Mil-Spec',
		['brand'] = 'Mammoth',
		['model'] = 'patriot3',
		['price'] = 81000,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `patriot3`,
		['shop'] = 'empty',
	},
	['outlaw'] = {
		['name'] = 'Outlaw',
		['brand'] = 'Nagasaki',
		['model'] = 'outlaw',
		['price'] = 21600,
		['class'] = 'd',
		['category'] = 'Off-Road',
		['hash'] = `outlaw`,
		['shop'] = 'pdm',
	},
	['bifta'] = {
		['name'] = 'Bifta',
		['brand'] = 'BF',
		['model'] = 'bifta',
		['price'] = 6480,
		['class'] = 'd',
		['category'] = 'Off-Road',
		['hash'] = `bifta`,
		['shop'] = 'pdm',
	},
	['kalahari'] = {
		['name'] = 'Kalahari',
		['brand'] = 'Canis',
		['model'] = 'kalahari',
		['price'] = 18000,
		['class'] = 'd',
		['category'] = 'Off-Road',
		['hash'] = `kalahari`,
		['shop'] = 'pdm',
	},
	['everon'] = {
		['name'] = 'Everon',
		['brand'] = 'Karin',
		['model'] = 'everon',
		['price'] = 54000,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `everon`,
		['shop'] = 'pdm',
	},
	['brawler'] = {
		['name'] = 'Brawler',
		['brand'] = 'Coil',
		['model'] = 'brawler',
		['price'] = 106920,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `brawler`,
		['shop'] = 'pdm',
	},
	['riata'] = {
		['name'] = 'Riata',
		['brand'] = 'Vapid',
		['model'] = 'riata',
		['price'] = 37800,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `riata`,
		['shop'] = 'pdm',
	},
-- Cycles
	['bmx'] = {
		['name'] = 'BMX',
		['brand'] = 'Unknown',
		['model'] = 'bmx',
		['price'] = 4176,
		['class'] = 'd',
		['category'] = 'Cycles',
		['hash'] = `bmx`,
		['shop'] = 'pdm',
	},
	['cruiser'] = {
		['name'] = 'Cruiser',
		['brand'] = 'Unknown',
		['model'] = 'cruiser',
		['price'] = 2700,
		['class'] = 'd',
		['category'] = 'Cycles',
		['hash'] = `cruiser`,
		['shop'] = 'pdm',
	},
	['fixter'] = {
		['name'] = 'Fixter',
		['brand'] = 'Unknown',
		['model'] = 'fixter',
		['price'] = 2700,
		['class'] = 'd',
		['category'] = 'Cycles',
		['hash'] = `fixter`,
		['shop'] = 'pdm',
	},
	['scorcher'] = {
		['name'] = 'Scorcher',
		['brand'] = 'Unknown',
		['model'] = 'scorcher',
		['price'] = 2700,
		['class'] = 'd',
		['category'] = 'Cycles',
		['hash'] = `scorcher`,
		['shop'] = 'pdm',
	},
	['tribike'] = {
		['name'] = 'Tribike',
		['brand'] = 'Unknown',
		['model'] = 'tribike',
		['price'] = 2700,
		['class'] = 'd',
		['category'] = 'Cycles',
		['hash'] = `tribike`,
		['shop'] = 'pdm',
	},
	['tribike2'] = {
		['name'] = 'Tribike',
		['brand'] = 'Unknown',
		['model'] = 'tribike2',
		['price'] = 2700,
		['class'] = 'd',
		['category'] = 'Cycles',
		['hash'] = `tribike2`,
		['shop'] = 'pdm',
	},
	['tribike3'] = {
		['name'] = 'Tribike',
		['brand'] = 'Unknown',
		['model'] = 'tribike3',
		['price'] = 2700,
		['class'] = 'd',
		['category'] = 'Cycles',
		['hash'] = `tribike3`,
		['shop'] = 'pdm',
	},
		
-- Service
	['trash'] = {
		['name'] = 'Trashmaster',
		['brand'] = 'JoBuilt',
		['model'] = 'trash',
		['price'] = 1000000,
		['class'] = 'd',
		['category'] = 'Service',
		['hash'] = `trash`,
		['shop'] = 'Service',
	},
	['stockade'] = {
		['name'] = 'Gruppesix',
		['brand'] = 'Brute',
		['model'] = 'stockade',
		['price'] = 1000000,
		['class'] = 'd',
		['category'] = 'Service',
		['hash'] = `stockade`,
		['shop'] = 'empty',
	},
-- Emergency
	['police'] = {
		['name'] = 'Police Cruiser',
		['brand'] = 'Vapid',
		['model'] = 'police',
		['price'] = 500,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `police`,
		['shop'] = 'police',
	},
	['policeb'] = {
		['name'] = 'Police Bike',
		['brand'] = 'Vapid',
		['model'] = 'policeb',
		['price'] = 500,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `policeb`,
		['shop'] = 'police',
	},
	['npolmm'] = {
		['name'] = 'Police Bike2',
		['brand'] = 'Vapid',
		['model'] = 'npolmm',
		['price'] = 500,
		['class'] = 'c',
		['category'] = 'Emergency',
		['hash'] = `npolmm`,
		['shop'] = 'police',
	},
	['police3'] = {
		['name'] = 'Police Cruiser',
		['brand'] = 'Vapid',
		['model'] = 'police3',
		['price'] = 1000,
		['class'] = 'a',
		['category'] = 'Emergency',
		['hash'] = `police3`,
		['shop'] = 'police',
	},
	['polvstr'] = {
		['name'] = 'Police V-STR',
		['brand'] = 'Vapid',
		['model'] = 'polvstr',
		['price'] = 1000,
		['class'] = 'a',
		['category'] = 'Emergency',
		['hash'] = `polvstr`,
		['shop'] = 'police',
	},
	['polcoquette'] = {
		['name'] = 'Police Coquette',
		['brand'] = 'Invetero',
		['model'] = 'polcoquette',
		['price'] = 1000,
		['class'] = 'a',
		['category'] = 'Emergency',
		['hash'] = `polcoquette`,
		['shop'] = 'police',
	},
	['polpenumbra'] = {
		['name'] = 'Police Penumbra',
		['brand'] = 'Maibatsu',
		['model'] = 'polpenumbra',
		['price'] = 1000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `polpenumbra`,
		['shop'] = 'police',
	},
	['polbuffalo4'] = {
		['name'] = 'Police Buffalo STX',
		['brand'] = 'Bravado',
		['model'] = 'polbuffalo4',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `polbuffalo4`,
		['shop'] = 'police',
	},
	['polscout2'] = {
		['name'] = 'Police Scout 2020',
		['brand'] = 'Vapid',
		['model'] = 'polscout2',
		['price'] = 1000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `polscout2`,
		['shop'] = 'police',
	},
	['polcaracara'] = {
		['name'] = 'Police Caracara',
		['brand'] = 'Vapid',
		['model'] = 'polcaracara',
		['price'] = 1000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `polcaracara`,
		['shop'] = 'police',
	},
	['ambulance'] = {
		['name'] = 'Ambulance',
		['brand'] = 'Brute',
		['model'] = 'ambulance',
		['price'] = 500,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `ambulance`,
		['shop'] = 'medic',
	},
	['rambulance'] = {
		['name'] = 'RAmbulance',
		['brand'] = 'Brute',
		['model'] = 'rambulance',
		['price'] = 1000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `rambulance`,
		['shop'] = 'medic',
	},
	['bfdsuv'] = {
		['name'] = 'bfdsuv',
		['brand'] = 'unknown',
		['model'] = 'bfdsuv',
		['price'] = 1000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `bfdsuv`,
		['shop'] = 'medic',
	},
	['nsandbrush4'] = {
		['name'] = 'nsandbrush4',
		['brand'] = 'unknown',
		['model'] = 'nsandbrush4',
		['price'] = 1000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `nsandbrush4`,
		['shop'] = 'medic',
	},
	['nsandbrush6 '] = {
		['name'] = 'nsandbrush6',
		['brand'] = 'unknown',
		['model'] = 'nsandbrush6',
		['price'] = 1000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `nsandbrush6`,
		['shop'] = 'medic',
	},
	['slrr'] = {
		['name'] = 'slrr',
		['brand'] = 'unknown',
		['model'] = 'slrr',
		['price'] = 1000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `slrr`,
		['shop'] = 'medic',
	},
	['rhinehart'] = {
		['name'] = 'Rhinehart',
		['brand'] = 'Ubermacht',
		['model'] = 'rhinehart',
		['price'] = 5000,
		['class'] = 'b',
		['category'] = 'Emergency',
		['hash'] = `rhinehart`,
		['shop'] = 'medic',
	},
	['aleutian'] = {
        ['name'] = 'Aleutian',
        ['brand'] = 'Vapid',
        ['model'] = 'aleutian',
        ['price'] = 10000,
        ['class'] = 'e',
        ['category'] = 'suvs',
        ['hash'] = `aleutian`,
        ['shop'] = 'police',
    },
    ['baller7'] = {
        ['name'] = 'Baller ST',
        ['brand'] = 'Gallivanter',
        ['model'] = 'baller7',
        ['price'] = 10000,
        ['class'] = 'b',
        ['category'] = 'suvs',
        ['hash'] = `baller7`,
        ['shop'] = 'police',
    },
	['dorado'] = {
        ['name'] = 'Dorado',
        ['brand'] = 'Vapid',
        ['model'] = 'dorado',
        ['price'] = 10000,
        ['class'] = 'd',
        ['category'] = 'suvs',
        ['hash'] = `dorado`,
        ['shop'] = 'police',
    },
    ['cavalcade3'] = {
        ['name'] = 'Cavalcade XL',
        ['brand'] = 'Albany',
        ['model'] = 'cavalcade3',
        ['price'] = 10000,
        ['class'] = 'c',
        ['category'] = 'suvs',
        ['hash'] = `cavalcade3`,
        ['shop'] = 'police',
    },
	['sandroamer'] = {
        ['name'] = 'Luxery BUS',
        ['brand'] = 'SAND',
        ['model'] = 'sandroamer',
        ['price'] = 1,
        ['class'] = 'a',
        ['category'] = 'suvs',
        ['hash'] = `sandroamer`,
        ['shop'] = 'empty',
    },
	['galaxyroamer'] = {
        ['name'] = 'Camper Home',
        ['brand'] = 'SAND',
        ['model'] = 'galaxyroamer',
        ['price'] = 1,
        ['class'] = 'a',
        ['category'] = 'suvs',
        ['hash'] = `galaxyroamer`,
        ['shop'] = 'empty',
    },
	
--Do Not Add
	['zr350'] = {
		['name'] = 'ZR350',
		['brand'] = 'Annis',
		['model'] = 'zr350',
		['price'] = 100000,
		['class'] = 's',
		['category'] = 'compacts',
		['hash'] = `zr350`,
		['shop'] = 'empty',
	},
	['impaler5'] = {
		['name'] = 'Impaler SZ',
		['brand'] = 'Declasse',
		['model'] = 'impaler5',
		['price'] = 100000,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `impaler5`,
		['shop'] = 'empty',
	},
	['impaler6'] = {
		['name'] = 'Impaler LX',
		['brand'] = 'Declasse',
		['model'] = 'impaler6',
		['price'] = 100000,
		['class'] = 'c',
		['category'] = 'muscle',
		['hash'] = `impaler6`,
		['shop'] = 'empty',
	},
---------gabz-------------------------------------------
['gbdominatorgsx'] = {
	['name'] = 'dominatorgsx',
	['brand'] = 'GB',
	['model'] = 'gbdominatorgsx',
	['price'] = 100000,
	['class'] = 'a',
	['category'] = 'muscle',
	['hash'] = `gbdominatorgsx`,
	['shop'] = 'empty',
},
['gbschwartzers'] = {
	['name'] = 'schwartzers',
	['brand'] = 'GB',
	['model'] = 'gbschwartzers',
	['price'] = 100000,
	['class'] = 'a',
	['category'] = 'muscle',
	['hash'] = `gbschwartzers`,
	['shop'] = 'empty',
},
['gbsentinelgts'] = {
	['name'] = 'sentinelgts',
	['brand'] = 'GB',
	['model'] = 'gbsentinelgts',
	['price'] = 100000,
	['class'] = 'a',
	['category'] = 'muscle',
	['hash'] = `gbsentinelgts`,
	['shop'] = 'empty',
},
---------boat-------------------------------------------
	['seashark'] = {
		['name'] = 'Sea Shark',
		['brand'] = 'Boat',
		['model'] = 'zr350',
		['price'] = 30000,
		['class'] = 'e',
		['category'] = 'boat',
		['hash'] = `seashark`,
		['shop'] = 'boat',
	},
	['dinghy'] = {
		['name'] = 'Dinghy',
		['brand'] = 'Boat',
		['model'] = 'zr350',
		['price'] = 35000,
		['class'] = 'e',
		['category'] = 'boat',
		['hash'] = `dinghy`,
		['shop'] = 'boat',
	},
	['jetmax'] = {
		['name'] = 'Jetmax',
		['brand'] = 'Boat',
		['model'] = 'zr350',
		['price'] = 40000,
		['class'] = 'e',
		['category'] = 'boat',
		['hash'] = `jetmax`,
		['shop'] = 'boat',
	},
	['marquis'] = {
		['name'] = 'Marquis',
		['brand'] = 'Boat',
		['model'] = 'zr350',
		['price'] = 50000,
		['class'] = 'e',
		['category'] = 'boat',
		['hash'] = `marquis`,
		['shop'] = 'boat',
	},
	['speeder'] = {
		['name'] = 'Speeder',
		['brand'] = 'Boat',
		['model'] = 'zr350',
		['price'] = 60000,
		['class'] = 'e',
		['category'] = 'boat',
		['hash'] = `speeder`,
		['shop'] = 'boat',
	},
	['toro'] = {
		['name'] = 'Toro',
		['brand'] = 'Boat',
		['model'] = 'zr350',
		['price'] = 80000,
		['class'] = 'e',
		['category'] = 'boat',
		['hash'] = `toro`,
		['shop'] = 'boat',
	},
	['longfin'] = {
		['name'] = 'Long fin',
		['brand'] = 'Boat',
		['model'] = 'zr350',
		['price'] = 100000,
		['class'] = 'e',
		['category'] = 'boat',
		['hash'] = `longfin`,
		['shop'] = 'boat',
	},
---------saman-------------------------------------------
	['fbi'] = { 
		['name'] = 'Federal Sedan',
		['brand'] = 'Vapid',
		['model'] = 'fbi',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `fbi`,
		['shop'] = 'empty',
	},
	['apoliceu15'] = { 
		['name'] = 'Apoliceu15',
		['brand'] = 'pd',
		['model'] = 'apoliceu15',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `apoliceu15`,
		['shop'] = 'empty',
	},
	['apoliceu14'] = { 
		['name'] = 'Apoliceu14',
		['brand'] = 'pd',
		['model'] = 'apoliceu14',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `apoliceu14`,
		['shop'] = 'empty',
	},
	['apoliceu13'] = { 
		['name'] = 'Apoliceu13',
		['brand'] = 'pd',
		['model'] = 'apoliceu13',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `apoliceu13`,
		['shop'] = 'empty',
	},
	['apoliceu9'] = { 
		['name'] = 'Apoliceu9',
		['brand'] = 'pd',
		['model'] = 'apoliceu9',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `apoliceu9`,
		['shop'] = 'empty',
	},
	['poldom'] = { 
		['name'] = 'Poldom',
		['brand'] = 'pd',
		['model'] = 'poldom',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `poldom`,
		['shop'] = 'empty',
	},
	['visione'] = { 
		['name'] = 'Visione',
		['brand'] = 'Grotti',
		['model'] = 'visione',
		['price'] = 1110000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `visione`,
		['shop'] = 'pdm',
	},    
	['turismo3'] = { 
		['name'] = 'Turismo Omaggio',
		['brand'] = 'Grotti',
		['model'] = 'turismo3',
		['price'] = 578000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `turismo3`,
		['shop'] = 'pdm',
	},
	['turismor'] = { 
		['name'] = 'Turismo R',
		['brand'] = 'Grotti',
		['model'] = 'turismor',
		['price'] = 472000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `turismor`,
		['shop'] = 'pdm',
	},
	['zorrusso'] = { 
		['name'] = 'Zorrusso',
		['brand'] = 'Pegassi',
		['model'] = 'zorrusso',
		['price'] = 390000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `zorrusso`,
		['shop'] = 'pdm',
	},
	['entity2'] = { 
		['name'] = 'Entity XXR',
		['brand'] = 'Overflod',
		['model'] = 'entity2',
		['price'] = 875000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `entity2`,
		['shop'] = 'pdm',
	},
	['entity3'] = { 
		['name'] = 'Entity MT',
		['brand'] = 'Overflod',
		['model'] = 'entity3',
		['price'] = 935000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `entity3`,
		['shop'] = 'pdm',
	},
	['nero'] = { 
		['name'] = 'Nero',
		['brand'] = 'Truffade',
		['model'] = 'nero',
		['price'] = 600000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `nero`,
		['shop'] = 'pdm',
	},
	['penetrator'] = { 
		['name'] = 'Penetrator',
		['brand'] = 'Ocelot',
		['model'] = 'penetrator',
		['price'] = 400000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `penetrator`,
		['shop'] = 'pdm',
	},
	['reaper'] = { 
		['name'] = 'Reaper',
		['brand'] = 'Pegassi',
		['model'] = 'reaper',
		['price'] = 200000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `reaper`,
		['shop'] = 'pdm',
	},
	['sc1'] = { 
		['name'] = 'SC1',
		['brand'] = 'Ubermacht',
		['model'] = 'sc1',
		['price'] = 354000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `sc1`,
		['shop'] = 'pdm',
	},
	['t20'] = { 
		['name'] = 'T20',
		['brand'] = 'Progen',
		['model'] = 't20',
		['price'] = 277000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `t20`,
		['shop'] = 'pdm',
	},
	['taipan'] = { 
		['name'] = 'Taipan',
		['brand'] = 'Cheval',
		['model'] = 'taipan',
		['price'] = 303000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `taipan`,
		['shop'] = 'pdm',
	},
	['tempesta'] = { 
		['name'] = 'Tempesta',
		['brand'] = 'Pegassi',
		['model'] = 'tempesta',
		['price'] = 505000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `tempesta`,
		['shop'] = 'pdm',
	},
	['thrax'] = { 
		['name'] = 'Thrax',
		['brand'] = 'Truffade',
		['model'] = 'thrax',
		['price'] = 454000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `thrax`,
		['shop'] = 'pdm',
	},
	['xa21'] = { 
		['name'] = 'XA-21',
		['brand'] = 'Ocelot',
		['model'] = 'xa21',
		['price'] = 182000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `xa21`,
		['shop'] = 'pdm',
	},
	['tigon'] = { 
		['name'] = 'Tigon',
		['brand'] = 'Lampadati',
		['model'] = 'tigon',
		['price'] = 660000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `tigon`,
		['shop'] = 'pdm',
	},
	['virtue'] = { 
		['name'] = 'Virtue',
		['brand'] = 'Ocelot',
		['model'] = 'virtue',
		['price'] = 450000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `virtue`,
		['shop'] = 'pdm',
	},
	['zeno'] = { 
		['name'] = 'Zeno',
		['brand'] = 'Overflod',
		['model'] = 'zeno',
		['price'] = 597000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `zeno`,
		['shop'] = 'pdm',
	},
	['tyrant'] = { 
		['name'] = 'Tyrant',
		['brand'] = 'Overflod',
		['model'] = 'tyrant',
		['price'] = 1297000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `tyrant`,
		['shop'] = 'pdm',
	},
	['tyrus'] = { 
		['name'] = 'Tyrus',
		['brand'] = 'Progen',
		['model'] = 'tyrus',
		['price'] = 1150000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `tyrus`,
		['shop'] = 'pdm',
	},
	['vagner'] = { 
		['name'] = 'Vagner',
		['brand'] = 'Dewbauchee',
		['model'] = 'vagner',
		['price'] = 1300000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `vagner`,
		['shop'] = 'pdm',
	},
	['primo'] = { 
		['name'] = 'Primo',
		['brand'] = 'Albany',
		['model'] = 'primo',
		['price'] = 15000,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `primo`,
		['shop'] = 'pdm',
	},
	['stanier'] = { 
		['name'] = 'Stanier',
		['brand'] = 'Vapid',
		['model'] = 'stanier',
		['price'] = 4000,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `stanier`,
		['shop'] = 'pdm',
	},
	['stratum'] = { 
		['name'] = 'Stratum',
		['brand'] = 'Zirconium',
		['model'] = 'stratum',
		['price'] = 167000,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `stratum`,
		['shop'] = 'pdm',
	},
	['warrener'] = { 
		['name'] = 'Warrener',
		['brand'] = 'Vulcar',
		['model'] = 'warrener',
		['price'] = 11000,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `warrener`,
		['shop'] = 'pdm',
	},
	['baller8'] = { 
		['name'] = 'Baller ST-D',
		['brand'] = 'Gallivanter',
		['model'] = 'baller8',
		['price'] = 120000,
		['class'] = 'a',
		['category'] = 'suvs',
		['hash'] = `baller8`,
		['shop'] = 'pdm',
	},
	['iwagen'] = { 
		['name'] = 'I-Wagen',
		['brand'] = 'Obey',
		['model'] = 'iwagen',
		['price'] = 30000,
		['class'] = 'a',
		['category'] = 'suvs',
		['hash'] = `iwagen`,
		['shop'] = 'pdm',
	},
	['issi8'] = { 
		['name'] = 'Issi Rally',
		['brand'] = 'Weeny',
		['model'] = 'issi8',
		['price'] = 57900,
		['class'] = 'b',
		['category'] = 'compacts',
		['hash'] = `issi8`,
		['shop'] = 'pdm',
	},
	['novak'] = { 
		['name'] = 'Novak',
		['brand'] = 'Lampadati',
		['model'] = 'novak',
		['price'] = 24900,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `novak`,
		['shop'] = 'pdm',
	},
	['rebla'] = { 
		['name'] = 'Rebla GTS',
		['brand'] = 'Ubermacht',
		['model'] = 'rebla',
		['price'] = 54900,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `rebla`,
		['shop'] = 'pdm',
	},
	['seminole2'] = { 
		['name'] = 'Seminole Frontier',
		['brand'] = 'Canis',
		['model'] = 'seminole2',
		['price'] = 20000,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `seminole2`,
		['shop'] = 'pdm',
	},
	['seminole2'] = { 
		['name'] = 'Seminole Frontier',
		['brand'] = 'Canis',
		['model'] = 'seminole2',
		['price'] = 20000,
		['class'] = 'c',
		['category'] = 'suvs',
		['hash'] = `seminole2`,
		['shop'] = 'pdm',
	},
	['toros'] = { 
		['name'] = 'Toros',
		['brand'] = 'Pegassi',
		['model'] = 'toros',
		['price'] = 365000,
		['class'] = 'a',
		['category'] = 'suvs',
		['hash'] = `toros`,
		['shop'] = 'pdm',
	},
	['autarch'] = { 
		['name'] = 'Autarch',
		['brand'] = 'Overflod',
		['model'] = 'autarch',
		['price'] = 690000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `autarch`,
		['shop'] = 'pdm',
	},
	['cyclone'] = { 
		['name'] = 'Cyclone',
		['brand'] = 'Coil',
		['model'] = 'cyclone',
		['price'] = 190000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `cyclone`,
		['shop'] = 'pdm',
	},
	['gp1'] = { 
		['name'] = 'GP1',
		['brand'] = 'Progen',
		['model'] = 'gp1',
		['price'] = 414000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `gp1`,
		['shop'] = 'pdm',
	},
	['dominator3'] = { 
		['name'] = 'Dominator GTX',
		['brand'] = 'Vapid',
		['model'] = 'dominator3',
		['price'] = 178000,
		['class'] = 'a',
		['category'] = 'muscle',
		['hash'] = `dominator3`,
		['shop'] = 'pdm',
	},
	['dominator7'] = { 
		['name'] = 'Dominator ASP',
		['brand'] = 'Vapid',
		['model'] = 'dominator7',
		['price'] = 98000,
		['class'] = 'a',
		['category'] = 'muscle',
		['hash'] = `dominator7`,
		['shop'] = 'pdm',
	},
	['dominator8'] = { 
		['name'] = 'Dominator GTT',
		['brand'] = 'Vapid',
		['model'] = 'dominator8',
		['price'] = 68000,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `dominator8`,
		['shop'] = 'pdm',
	},
	['dominator9'] = { 
		['name'] = 'Dominator GT',
		['brand'] = 'Vapid',
		['model'] = 'dominator9',
		['price'] = 287000,
		['class'] = 'a',
		['category'] = 'muscle',
		['hash'] = `dominator9`,
		['shop'] = 'pdm',
	},
	['boor'] = { 
		['name'] = 'Boor',
		['brand'] = 'Karin',
		['model'] = 'boor',
		['price'] = 9000,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `boor`,
		['shop'] = 'pdm',
	},
	['hellion'] = { 
		['name'] = 'Hellion',
		['brand'] = 'Annis',
		['model'] = 'hellion',
		['price'] = 68000,
		['class'] = 'c',
		['category'] = 'Off-Road',
		['hash'] = `hellion`,
		['shop'] = 'pdm',
	},
	['trophytruck'] = { 
		['name'] = 'Desert Raid',
		['brand'] = 'Vapid',
		['model'] = 'trophytruck',
		['price'] = 38000,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `trophytruck`,
		['shop'] = 'pdm',
	},
	['dubsta'] = { 
		['name'] = 'Dubsta',
		['brand'] = 'Benefactor',
		['model'] = 'dubsta',
		['price'] = 48000,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `dubsta`,
		['shop'] = 'pdm',
	},
	['dubsta2'] = { 
		['name'] = 'Dubsta G',
		['brand'] = 'Benefactor',
		['model'] = 'dubsta2',
		['price'] = 53000,
		['class'] = 'b',
		['category'] = 'suvs',
		['hash'] = `dubsta2`,
		['shop'] = 'pdm',
	},
	['dubsta3'] = { 
		['name'] = 'Dubsta 6x6',
		['brand'] = 'Benefactor',
		['model'] = 'dubsta3',
		['price'] = 66666,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `dubsta3`,
		['shop'] = 'pdm',
	},
	['kamacho'] = { 
		['name'] = 'Kamacho',
		['brand'] = 'Canis',
		['model'] = 'kamacho',
		['price'] = 176800,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `kamacho`,
		['shop'] = 'pdm',
	},
	['bodhi2'] = { 
		['name'] = 'Bodhi',
		['brand'] = 'Canis',
		['model'] = 'bodhi2',
		['price'] = 46000,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `bodhi2`,
		['shop'] = 'pdm',
	},
	['monstrociti'] = { 
		['name'] = 'Monstro Citi',
		['brand'] = 'Maibatsu',
		['model'] = 'monstrociti',
		['price'] = 92000,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `monstrociti`,
		['shop'] = 'pdm',
	},
	['l35'] = { 
		['name'] = 'Walton L35',
		['brand'] = 'Declasse',
		['model'] = 'l35',
		['price'] = 123000,
		['class'] = 'b',
		['category'] = 'Off-Road',
		['hash'] = `l35`,
		['shop'] = 'pdm',
	},
	['intruder'] = { 
		['name'] = 'Intruder',
		['brand'] = 'Karin',
		['model'] = 'intruder',
		['price'] = 8000,
		['class'] = 'c',
		['category'] = 'sedans',
		['hash'] = `intruder`,
		['shop'] = 'pdm',
	},
	['kanjo'] = { 
		['name'] = 'Blista Kanjo',
		['brand'] = 'Dinka',
		['model'] = 'kanjo',
		['price'] = 42000,
		['class'] = 'b',
		['category'] = 'compacts',
		['hash'] = `kanjo`,
		['shop'] = 'pdm',
	},
	['rhapsody'] = { 
		['name'] = 'Rhapsody',
		['brand'] = 'Declasse',
		['model'] = 'rhapsody',
		['price'] = 15000,
		['class'] = 'b',
		['category'] = 'compacts',
		['hash'] = `rhapsody`,
		['shop'] = 'pdm',
	},
	['fr36'] = { 
		['name'] = 'FR36',
		['brand'] = 'Fathom',
		['model'] = 'fr36',
		['price'] = 25000,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `fr36`,
		['shop'] = 'pdm',
	},
	['previon'] = { 
		['name'] = 'Previon',
		['brand'] = 'Karin',
		['model'] = 'previon',
		['price'] = 28000,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `previon`,
		['shop'] = 'pdm',
	},
	['zion'] = { 
		['name'] = 'Zion',
		['brand'] = 'Ubermacht',
		['model'] = 'zion',
		['price'] = 18000,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `zion`,
		['shop'] = 'pdm',
	},
	['zion2'] = { 
		['name'] = 'Zion Cabrio',
		['brand'] = 'Ubermacht',
		['model'] = 'zion2',
		['price'] = 19500,
		['class'] = 'b',
		['category'] = 'coupes',
		['hash'] = `zion2`,
		['shop'] = 'pdm',
	},
	['brigham'] = { 
		['name'] = 'Brigham',
		['brand'] = 'Albany',
		['model'] = 'brigham',
		['price'] = 47500,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `brigham`,
		['shop'] = 'pdm',
	},
	['stalion'] = { 
		['name'] = 'Stalion',
		['brand'] = 'Declasse',
		['model'] = 'stalion',
		['price'] = 67500,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `stalion`,
		['shop'] = 'pdm',
	},
	['deviant'] = { 
		['name'] = 'Deviant',
		['brand'] = 'Schyster',
		['model'] = 'deviant',
		['price'] = 59700,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `deviant`,
		['shop'] = 'pdm',
	},
	['stxbanshee'] = { 
		['name'] = 'Banshee STX',
		['brand'] = 'Bravado',
		['model'] = 'stxbanshee',
		['price'] = 673700,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `stxbanshee`,
		['shop'] = 'pdm',
	},
	['faction'] = { 
		['name'] = 'Faction',
		['brand'] = 'Bravado',
		['model'] = 'faction',
		['price'] = 75000,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `faction`,
		['shop'] = 'pdm',
	},
	['greenwood'] = { 
		['name'] = 'Greenwood',
		['brand'] = 'Bravado',
		['model'] = 'greenwood',
		['price'] = 8000,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `greenwood`,
		['shop'] = 'pdm',
	},
	['impaler'] = { 
		['name'] = 'impaler',
		['brand'] = 'Declasse',
		['model'] = 'impaler',
		['price'] = 13000,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `impaler`,
		['shop'] = 'pdm',
	},
	['nightshade'] = { 
		['name'] = 'Nightshade',
		['brand'] = 'Imponte',
		['model'] = 'nightshade',
		['price'] = 83000,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `nightshade`,
		['shop'] = 'pdm',
	},
	['phoenix'] = { 
		['name'] = 'Phoenix',
		['brand'] = 'Imponte',
		['model'] = 'phoenix',
		['price'] = 33000,
		['class'] = 'b',
		['category'] = 'muscle',
		['hash'] = `phoenix`,
		['shop'] = 'pdm',
	},
	['gt500'] = { 
		['name'] = 'GT500',
		['brand'] = 'Grotti',
		['model'] = 'gt500',
		['price'] = 146000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `gt500`,
		['shop'] = 'pdm',
	},
	['mamba'] = { 
		['name'] = 'Mamba',
		['brand'] = 'Declasse',
		['model'] = 'mamba',
		['price'] = 297000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `mamba`,
		['shop'] = 'pdm',
	},
	['michelli'] = { 
		['name'] = 'Michelli',
		['brand'] = 'Lampadati',
		['model'] = 'michelli',
		['price'] = 57000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `michelli`,
		['shop'] = 'pdm',
	},
	['manana'] = { 
		['name'] = 'Manana',
		['brand'] = 'Albany',
		['model'] = 'manana',
		['price'] = 17000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `manana`,
		['shop'] = 'pdm',
	},
	['peyote'] = { 
		['name'] = 'Peyote',
		['brand'] = 'Vapid',
		['model'] = 'peyote',
		['price'] = 14000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `peyote`,
		['shop'] = 'pdm',
	},
	['retinue'] = { 
		['name'] = 'Retinue',
		['brand'] = 'Vapid',
		['model'] = 'retinue',
		['price'] = 160000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `retinue`,
		['shop'] = 'pdm',
	},
	['retinue2'] = { 
		['name'] = 'Retinue MK II',
		['brand'] = 'Vapid',
		['model'] = 'retinue2',
		['price'] = 175000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `retinue2`,
		['shop'] = 'pdm',
	},
	['rapidgt3'] = { 
		['name'] = 'Rapid GT Classic',
		['brand'] = 'Dewbauchee',
		['model'] = 'rapidgt3',
		['price'] = 183700,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `rapidgt3`,
		['shop'] = 'pdm',
	},
	['savestra'] = { 
		['name'] = 'Savestra',
		['brand'] = 'Annis',
		['model'] = 'savestra',
		['price'] = 175000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `savestra`,
		['shop'] = 'pdm',
	},
	['swinger'] = { 
		['name'] = 'Swinger',
		['brand'] = 'Ocelot',
		['model'] = 'swinger',
		['price'] = 232000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `swinger`,
		['shop'] = 'pdm',
	},
	['torero'] = { 
		['name'] = 'Torero',
		['brand'] = 'Pegassi',
		['model'] = 'torero',
		['price'] = 296000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `torero`,
		['shop'] = 'pdm',
	},
	['torero2'] = { 
        ['name'] = 'Torero XO',
        ['brand'] = 'Pegassi',
        ['model'] = 'torero2',
        ['price'] = 1570000,
        ['class'] = 's',
        ['category'] = 'super',
        ['hash'] = `torero2`,
        ['shop'] = 'pdm',
    },
	['zion3'] = { 
		['name'] = 'Zion Classic',
		['brand'] = 'Ubermacht',
		['model'] = 'zion3',
		['price'] = 168000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `zion3`,
		['shop'] = 'pdm',
	},
	['turismo2'] = { 
		['name'] = 'Turismo Classic',
		['brand'] = 'Grotti',
		['model'] = 'turismo2',
		['price'] = 453000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `turismo2`,
		['shop'] = 'pdm',
	},
	['postlude'] = { 
		['name'] = 'Postlude',
		['brand'] = 'Dinka',
		['model'] = 'postlude',
		['price'] = 11000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `postlude`,
		['shop'] = 'pdm',
	},
	['schlagen'] = { 
		['name'] = 'Schlagen',
		['brand'] = 'Benefactor',
		['model'] = 'schlagen',
		['price'] = 206000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `schlagen`,
		['shop'] = 'pdm',
	},
	['schafter2'] = { 
		['name'] = 'Schafter V12',
		['brand'] = 'Benefactor',
		['model'] = 'schafter2',
		['price'] = 185000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `schafter2`,
		['shop'] = 'pdm',
	},
	['schafter3'] = { 
		['name'] = 'Schafter GT',
		['brand'] = 'Benefactor',
		['model'] = 'schafter3',
		['price'] = 200000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `schafter3`,
		['shop'] = 'pdm',
	},
	['schafter4'] = { 
		['name'] = 'Schafter V8',
		['brand'] = 'Benefactor',
		['model'] = 'schafter4',
		['price'] = 108000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `schafter4`,
		['shop'] = 'pdm',
	},
	['sm722'] = { 
		['name'] = 'SM 722',
		['brand'] = 'Benefactor',
		['model'] = 'sm722',
		['price'] = 698000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `sm722`,
		['shop'] = 'pdm',
	},
	['vectre'] = { 
		['name'] = 'Vectre',
		['brand'] = ' Emperor',
		['model'] = 'vectre',
		['price'] = 184000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `vectre`,
		['shop'] = 'pdm',
	},
	['zr350'] = { 
		['name'] = 'ZR 350',
		['brand'] = 'Annis',
		['model'] = 'zr350',
		['price'] = 284000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `zr350`,
		['shop'] = 'pdm',
	},
	['sentinel2'] = { 
		['name'] = 'Sentinel GT',
		['brand'] = 'Ubermacht',
		['model'] = 'sentinel2',
		['price'] = 97000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `sentinel2`,
		['shop'] = 'pdm',
	},
	['sentinel3'] = { 
		['name'] = 'Sentinel Classic',
		['brand'] = 'Ubermacht',
		['model'] = 'sentinel3',
		['price'] = 490000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `sentinel3`,
		['shop'] = 'pdm',
	},
	['feltzer3'] = { 
		['name'] = 'Stirling GT',
		['brand'] = 'Benefactor',
		['model'] = 'feltzer3',
		['price'] = 145000,
		['class'] = 's',
		['category'] = 'SportsClassics',
		['hash'] = `feltzer3`,
		['shop'] = 'pdm',
	},
	['casco'] = { 
		['name'] = 'Casco',
		['brand'] = 'Lampadati',
		['model'] = 'casco',
		['price'] = 45000,
		['class'] = 's',
		['category'] = 'SportsClassics',
		['hash'] = `casco`,
		['shop'] = 'pdm',
	},
	['coquette2'] = { 
		['name'] = 'Coquette Classic',
		['brand'] = 'Invetero',
		['model'] = 'coquette2',
		['price'] = 55000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `coquette2`,
		['shop'] = 'pdm',
	},
	['coquette5'] = { 
		['name'] = 'Coquette D1',
		['brand'] = 'Invetero',
		['model'] = 'coquette5',
		['price'] = 65000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `coquette5`,
		['shop'] = 'pdm',
	},
	['cheetah2'] = { 
		['name'] = 'Cheetah Classic',
		['brand'] = 'Grotti',
		['model'] = 'cheetah2',
		['price'] = 238000,
		['class'] = 'b',
		['category'] = 'SportsClassics',
		['hash'] = `cheetah2`,
		['shop'] = 'pdm',
	},
	['issi7'] = { 
		['name'] = 'Issi Sport',
		['brand'] = 'Weeny',
		['model'] = 'issi7',
		['price'] = 73000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `issi7`,
		['shop'] = 'pdm',
	},
	['italigto'] = { 
		['name'] = 'Itali GTO',
		['brand'] = 'Grotti',
		['model'] = 'italigto',
		['price'] = 590000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `italigto`,
		['shop'] = 'pdm',
	},
	['stingertt'] = { 
		['name'] = 'Stinger TT',
		['brand'] = 'Grotti',
		['model'] = 'stingertt',
		['price'] = 825000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `stingertt`,
		['shop'] = 'pdm',
	},
	['jester'] = { 
		['name'] = 'Jester',
		['brand'] = 'Dinka',
		['model'] = 'jester',
		['price'] = 180000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `jester`,
		['shop'] = 'pdm',
	},
	['jester4'] = { 
		['name'] = 'Jester RR',
		['brand'] = 'Dinka',
		['model'] = 'jester4',
		['price'] = 200000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `jester4`,
		['shop'] = 'pdm',
	},
	['komoda'] = { 
		['name'] = 'Komoda',
		['brand'] = 'Lampadati',
		['model'] = 'komoda',
		['price'] = 157000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `komoda`,
		['shop'] = 'pdm',
	},
	['kuruma'] = { 
		['name'] = 'Kuruma',
		['brand'] = 'Karin',
		['model'] = 'kuruma',
		['price'] = 666000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `kuruma`,
		['shop'] = 'pdm',
	},
	['neo'] = { 
		['name'] = 'Neo',
		['brand'] = 'Vysser',
		['model'] = 'neo',
		['price'] = 798000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `neo`,
		['shop'] = 'pdm',
	},
	['panthere'] = { 
		['name'] = 'Panthere',
		['brand'] = 'Toundra',
		['model'] = 'panthere',
		['price'] = 296500,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `panthere`,
		['shop'] = 'pdm',
	},
	['pariah'] = { 
		['name'] = 'Pariah',
		['brand'] = 'Ocelot',
		['model'] = 'pariah',
		['price'] = 127500,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `pariah`,
		['shop'] = 'pdm',
	},
	['rt3000'] = { 
		['name'] = 'RT 3000',
		['brand'] = 'Dinka',
		['model'] = 'rt3000',
		['price'] = 374500,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `rt3000`,
		['shop'] = 'pdm',
	},
	['remus'] = { 
		['name'] = 'Remus',
		['brand'] = 'Annis',
		['model'] = 'remus',
		['price'] = 54500,
		['class'] = 's',
		['category'] = 'SportsClassics',
		['hash'] = `remus`,
		['shop'] = 'pdm',
	},
	['tenf'] = { 
		['name'] = '10 F',
		['brand'] = 'Obey',
		['model'] = 'tenf',
		['price'] = 710000,
		['class'] = 's',
		['category'] = 'sport',
		['hash'] = `tenf`,
		['shop'] = 'pdm',
	},
	['tenf2'] = { 
		['name'] = '10 F Widebody',
		['brand'] = 'Obey',
		['model'] = 'tenf2',
		['price'] = 740000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `tenf2`,
		['shop'] = 'pdm',
	},
	['drafter'] = {
		['name'] = '8F Drafter',
		['brand'] = 'Obey',
		['model'] = 'drafter',
		['price'] = 105000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `drafter`,
		['shop'] = 'pdm',
	},
	['banshee'] = {
		['name'] = 'Banshee',
		['brand'] = 'Bravado',
		['model'] = 'banshee',
		['price'] = 540000,
		['class'] = 's',
		['category'] = 'super',
		['hash'] = `banshee`,
		['shop'] = 'pdm',
	},
	['bestiagts'] = { 
		['name'] = 'Bestia GTS',
		['brand'] = 'Grotti',
		['model'] = 'bestiagts',
		['price'] = 98000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `bestiagts`,
		['shop'] = 'pdm',
	},
	['lynx'] = { 
		['name'] = 'Lynx',
		['brand'] = 'Grotti',
		['model'] = 'lynx',
		['price'] = 65000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `lynx`,
		['shop'] = 'pdm',
	},
	['calico'] = { 
		['name'] = 'Calico GTF',
		['brand'] = 'Karin',
		['model'] = 'calico',
		['price'] = 565000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `calico`,
		['shop'] = 'pdm',
	},
	['corsita'] = { 
		['name'] = 'Corsita',
		['brand'] = 'Lampadati',
		['model'] = 'corsita',
		['price'] = 365000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `corsita`,
		['shop'] = 'pdm',
	},
	['cypher'] = { 
		['name'] = 'Cypher',
		['brand'] = 'Ubermacht',
		['model'] = 'cypher',
		['price'] = 176000,
		['class'] = 's',
		['category'] = 'sport',
		['hash'] = `cypher`,
		['shop'] = 'pdm',
	},
	['elegy'] = { 
		['name'] = 'Elegy Retro',
		['brand'] = 'Annis',
		['model'] = 'elegy',
		['price'] = 480000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `elegy`,
		['shop'] = 'pdm',
	},
	['euros'] = { 
		['name'] = 'Euros',
		['brand'] = 'Annis',
		['model'] = 'euros',
		['price'] = 508000,
		['class'] = 's',
		['category'] = 'Sports',
		['hash'] = `euros`,
		['shop'] = 'pdm',
	},
	['gauntlet2'] = { 
		['name'] = 'Gauntlet Daytona',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet2',
		['price'] = 128000,
		['class'] = 's',
		['category'] = 'muscle',
		['hash'] = `gauntlet2`,
		['shop'] = 'pdm',
	},
	['gauntlet3'] = { 
		['name'] = 'Gauntlet Classic',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet3',
		['price'] = 58000,
		['class'] = 's',
		['category'] = 'muscle',
		['hash'] = `gauntlet3`,
		['shop'] = 'pdm',
	},
	['gauntlet4'] = { 
		['name'] = 'Gauntlet Hellfire',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet4',
		['price'] = 184000,
		['class'] = 's',
		['category'] = 'muscle',
		['hash'] = `gauntlet4`,
		['shop'] = 'pdm',
	},
	['gauntlet5'] = { 
		['name'] = 'Gauntlet Classic Custom',
		['brand'] = 'Bravado',
		['model'] = 'gauntlet5',
		['price'] = 63000,
		['class'] = 's',
		['category'] = 'muscle',
		['hash'] = `gauntlet5`,
		['shop'] = 'pdm',
	},
	['cliffhanger'] = { 
		['name'] = 'Cliffhanger',
		['brand'] = 'Western',
		['model'] = 'cliffhanger',
		['price'] = 225000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `cliffhanger`,
		['shop'] = 'pdm',
	},
	['diablous'] = { 
		['name'] = 'Diablous',
		['brand'] = 'Principe',
		['model'] = 'diablous',
		['price'] = 33000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `diablous`,
		['shop'] = 'pdm',
	},
	['diablous2'] = { 
		['name'] = 'Diablous Custom',
		['brand'] = 'Principe',
		['model'] = 'diablous2',
		['price'] = 165000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `diablous2`,
		['shop'] = 'pdm',
	},
	['fcr2'] = { 
		['name'] = 'FCR 1000 Custom',
		['brand'] = 'Pegassi',
		['model'] = 'fcr2',
		['price'] = 63000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `fcr2`,
		['shop'] = 'pdm',
	},
	['gargoyle'] = { 
		['name'] = 'Gargoyle',
		['brand'] = 'Western',
		['model'] = 'gargoyle',
		['price'] = 20000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `gargoyle`,
		['shop'] = 'pdm',
	},
	['innovation'] = { 
		['name'] = 'Innovation',
		['brand'] = 'LCC',
		['model'] = 'innovation',
		['price'] = 10000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `innovation`,
		['shop'] = 'pdm',
	},
	['enduro'] = { 
		['name'] = 'Enduro',
		['brand'] = 'Dinka',
		['model'] = 'enduro',
		['price'] = 28000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `enduro`,
		['shop'] = 'pdm',
	},
	['defiler'] = { 
		['name'] = 'Defiler',
		['brand'] = 'Shitzu',
		['model'] = 'defiler',
		['price'] = 175000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `defiler`,
		['shop'] = 'pdm',
	},
	['daemon2'] = { 
		['name'] = 'Daemon Regular',
		['brand'] = 'Western',
		['model'] = 'daemon2',
		['price'] = 135000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `daemon2`,
		['shop'] = 'pdm',
	},
	['avarus'] = { 
		['name'] = 'Avarus',
		['brand'] = 'LCC',
		['model'] = 'avarus',
		['price'] = 333000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `avarus`,
		['shop'] = 'pdm',
	},
	['esskey'] = { 
		['name'] = 'Esskey',
		['brand'] = 'Pegassi',
		['model'] = 'esskey',
		['price'] = 33000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `esskey`,
		['shop'] = 'pdm',
	},
	['hexer'] = { 
		['name'] = 'Hexer',
		['brand'] = 'LCC',
		['model'] = 'hexer',
		['price'] = 25000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `hexer`,
		['shop'] = 'pdm',
	},
	['nightblade'] = { 
		['name'] = 'Nightblade',
		['brand'] = 'Western',
		['model'] = 'nightblade',
		['price'] = 222000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `nightblade`,
		['shop'] = 'pdm',
	},
	['manchez2'] = { 
		['name'] = 'Manchez Scout',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez2',
		['price'] = 375000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `manchez2`,
		['shop'] = 'pdm',
	},
	['manchez3'] = { 
		['name'] = 'Manchez Scout C',
		['brand'] = 'Maibatsu',
		['model'] = 'manchez3',
		['price'] = 355000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `manchez3`,
		['shop'] = 'pdm',
	},
	['powersurge'] = { 
		['name'] = 'Powersurge',
		['brand'] = 'Western',
		['model'] = 'powersurge',
		['price'] = 171000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `powersurge`,
		['shop'] = 'pdm',
	},
	['reever'] = { 
		['name'] = 'Reever',
		['brand'] = 'Western',
		['model'] = 'reever',
		['price'] = 120000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `reever`,
		['shop'] = 'pdm',
	},
	['vortex'] = { 
		['name'] = 'Vortex',
		['brand'] = 'Pegassi',
		['model'] = 'vortex',
		['price'] = 44000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `vortex`,
		['shop'] = 'pdm',
	},
	['wolfsbane'] = { 
		['name'] = 'Wolfsbane',
		['brand'] = 'Western',
		['model'] = 'wolfsbane',
		['price'] = 53000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `wolfsbane`,
		['shop'] = 'pdm',
	},
	['zombiea'] = { 
		['name'] = 'Zombie Bobber',
		['brand'] = 'Western',
		['model'] = 'zombiea',
		['price'] = 35000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `zombiea`,
		['shop'] = 'pdm',
	},
	['zombieb'] = { 
		['name'] = 'Zombie Chopper',
		['brand'] = 'Western',
		['model'] = 'zombieb',
		['price'] = 55000,
		['class'] = 'a',
		['category'] = 'Motorcycles',
		['hash'] = `zombieb`,
		['shop'] = 'pdm',
	},
	['shinobi'] = { 
		['name'] = 'Shinobi',
		['brand'] = 'Nagasaki',
		['model'] = 'shinobi',
		['price'] = 353000,
		['class'] = 's',
		['category'] = 'Motorcycles',
		['hash'] = `shinobi`,
		['shop'] = 'pdm',
	},
	['ratbike'] = { 
		['name'] = 'Rat Bike',
		['brand'] = 'Western',
		['model'] = 'ratbike',
		['price'] = 500000,
		['class'] = 's',
		['category'] = 'Motorcycles',
		['hash'] = `ratbike`,
		['shop'] = 'pdm',
	}, 
	['shotaro'] = { 
		['name'] = 'Shotaro',
		['brand'] = 'Nagasaki',
		['model'] = 'shotaro',
		['price'] = 750000,
		['class'] = 's',
		['category'] = 'Motorcycles',
		['hash'] = `shotaro`,
		['shop'] = 'pdm',
	},
	['inductor'] = { 
		['name'] = 'Inductor',
		['brand'] = 'Coil',
		['model'] = 'inductor',
		['price'] = 12000,
		['class'] = 'b',
		['category'] = 'Cycles',
		['hash'] = `inductor`,
		['shop'] = 'pdm',
	},
	['inductor2'] = { 
		['name'] = 'Inductor Junk Energy',
		['brand'] = 'Coil',
		['model'] = 'inductor2',
		['price'] = 15000,
		['class'] = 'b',
		['category'] = 'Cycles',
		['hash'] = `inductor2`,
		['shop'] = 'pdm',
	},
	['nebula'] = { 
		['name'] = 'Nebula',
		['brand'] = 'Vulcar',
		['model'] = 'nebula',
		['price'] = 80000,
		['class'] = 'a',
		['category'] = 'Cycles',
		['hash'] = `nebula`,
		['shop'] = 'empty',
	},
	['nkbuffalos'] = { 
		['name'] = 'Nebula',
		['brand'] = 'Vapid',
		['model'] = 'nkbuffalos',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `nkbuffalos`,
		['shop'] = 'police',
	},
	['fbi2'] = { 
		['name'] = 'Federal SUV',
		['brand'] = 'Vapid',
		['model'] = 'fbi2',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `fbi2`,
		['shop'] = 'empty',
	},
	['emsnspeedo'] = { 
		['name'] = 'EMS Speedo',
		['brand'] = 'Speedo',
		['model'] = 'emsnspeedo',
		['price'] = 1000,
		['class'] = 's',
		['category'] = 'Emergency',
		['hash'] = `emsnspeedo`,
		['shop'] = 'medic',
	},
------------------------------------------------------gabz------------------------------------------------------
['gbterrorizer'] = {   
    ['name'] = 'Terrorizer',  
    ['brand'] = 'HVY',  
    ['model'] = 'gbterrorizer',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbterrorizer`,  
    ['shop'] = 'police', 
},
['gbpolbisonhf'] = {   
    ['name'] = 'Police Bison HF',  
    ['brand'] = 'BRAVADO',  
    ['model'] = 'gbpolbisonhf',  
    ['price'] = 5000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolbisonhf`,  
    ['shop'] = 'police', 
},
['gbemsbisonstx'] = {   
    ['name'] = 'Bison EMS',  
    ['brand'] = 'BRAVADO',  
    ['model'] = 'gbemsbisonstx',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbemsbisonstx`,  
    ['shop'] = 'medic', 
},
['gbpolbisonstx'] = {   
    ['name'] = 'Police Bison STX',  
    ['brand'] = 'BRAVADO',  
    ['model'] = 'gbpolbisonstx',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolbisonstx`,  
    ['shop'] = 'police', 
},
['gbpolcometcl'] = {   
    ['name'] = 'Police Comet Classic',  
    ['brand'] = 'PFISTER',  
    ['model'] = 'gbpolcometcl',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolcometcl`,  
    ['shop'] = 'police', 
},
['gbpolcomets2r'] = {   
    ['name'] = 'Police Comet S2-R',  
    ['brand'] = 'PFISTER',  
    ['model'] = 'gbpolcomets2r',  
    ['price'] = 1000,
    ['class'] = 's', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolcomets2r`,  
    ['shop'] = 'police', 
},
['gbpoldominatorgsx'] = {   
    ['name'] = 'Police Dominator GSX',  
    ['brand'] = 'VAPID',  
    ['model'] = 'gbpoldominatorgsx',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpoldominatorgsx`,  
    ['shop'] = 'police', 
},
['gbpolprospero'] = {   
    ['name'] = 'Police Prospero',  
    ['brand'] = 'PEGASSI',  
    ['model'] = 'gbpolprospero',  
    ['price'] = 1000,
    ['class'] = 's', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolprospero`,  
    ['shop'] = 'police', 
},
['gbpolsolace'] = {   
    ['name'] = 'Police Solace',  
    ['brand'] = 'DEWBAUCH',  
    ['model'] = 'gbpolsolace',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolsolace`,  
    ['shop'] = 'tuner', 
},
['gbpolstanierle'] = {   
    ['name'] = 'Police Stanier LE',  
    ['brand'] = 'VAPID',  
    ['model'] = 'gbpolstanierle',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolstanierle`,  
    ['shop'] = 'police', 
},
['gbpolstarlight'] = {   
    ['name'] = 'Police Starlight',  
    ['brand'] = 'VULCAR',  
    ['model'] = 'gbpolstarlight',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolstarlight`,  
    ['shop'] = 'police', 
},
['gbpolsultanrsx'] = {   
    ['name'] = 'Police Sultan RSx',  
    ['brand'] = 'KARIN',  
    ['model'] = 'gbpolsultanrsx',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolsultanrsx`,  
    ['shop'] = 'police', 
},
['gbpoltahomagt'] = {   
    ['name'] = 'Police Tahoma GT',  
    ['brand'] = 'DECLASSE',  
    ['model'] = 'gbpoltahomagt',  
    ['price'] = 1000,
    ['class'] = 'b', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpoltahomagt`,  
    ['shop'] = 'police', 
},
['gbpoltr3s'] = {   
    ['name'] = 'Police TR3-S',  
    ['brand'] = 'PROGEN',  
    ['model'] = 'gbpoltr3s',  
    ['price'] = 5000,
    ['class'] = 's', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpoltr3s`,  
    ['shop'] = 'police', 
},
['gbpolturismogt'] = {   
    ['name'] = 'Police Turismo 300GT',  
    ['brand'] = 'GROTTI',  
    ['model'] = 'gbpolturismogt',  
    ['price'] = 1000,
    ['class'] = 's', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbpolturismogt`,  
    ['shop'] = 'police', 
},
['gbfirevoyager'] = {   
    ['name'] = 'Voyager Fire Truck',  
    ['brand'] = 'MTL',  
    ['model'] = 'gbfirevoyager',  
    ['price'] = 1000,
    ['class'] = 'a', 
    ['category'] = 'Emergency', 
    ['hash'] = `gbfirevoyager`,  
    ['shop'] = 'medic', 
},
}
for _, v in pairs(QBShared.Vehicles) do
	QBShared.VehicleHashes[v.hash] = v
end