RegisterNetEvent("qb-stretcher:server:Patientbed", function(psource,coord)
     TriggerClientEvent("qb-stretcher:client:bed", psource, nil,false,coord)
end)
RegisterNetEvent("qb-stretcher:server:PatientSit", function(psource,side,coord)
    TriggerClientEvent("qb-stretcher:client:seat", psource, nil,side,false,coord)
end)
RegisterNetEvent("qb-stretcher:server:TakeOutPatient", function(psource)
    TriggerClientEvent("qb-stretcher:client:unbed", psource)
end)
RegisterNetEvent("qb-stretcher:server:Backboard", function(psource,coord)
    TriggerClientEvent("qb-stretcher:client:changebed", psource,false,coord)
end)
