-- A+ is A vehicles but with tuning, same for S+
Config.Vehicles = {
    ["D"] = {
        "dilettante",
        "weevil",
        "rebel2",
        "panto",
        "bfinjection",
        "outlaw",
        "bifta",
        "kalahari",
        "burrito",
        "regina",
        "buccaneer",
    },
    ["C"] = {
        "surage",
        "fugitive",
        "brioso3",
        "asea",
        "prairie",
        "chino",
        "ingot",
        "seminole",
        "fq2",
        "habanero",
        "buccaneer",
    },
    ["B"] = {
        "buffalo",
        "buffalo2",
        "oracle",
        "dominator",
        "cavalcade",
        "granger",
        "phoenix",
        "F620",
        "Ruiner",
        "sabregt",
        "felon2",
        "voodoo2",
        "yosemite",
    },
    ["A"] = {
        "warrener",
        "tornado6",
        "rapidgt",
        "rapidgt2",
        "alpha",
        "manana",
        "deity",
        "issi8",
        "nebula",
        "carbonizzare",
        "surano",
    },
    ["A+"] = {
        "peyote2",
        "tampa",
        "dominator",
        "dominator3",
        "brioso",
        "windsor",
        "zion2",
        "infernus2",
        "penumbra",
    },
    ["S"] = {
        "tornado6",
        "dominator",
        "dominator3",
        "peyote2",
        "bullet",
        "furia",
        "jugular",
        "penumbra2",

    },
    ["S+"] = {
        "sultan",
        "sultanrs",
        "peyote2",
        "infernus",
        "coquette4",
        "growler",
        "elegy2",
    },
}