Config = {}

Config.Decays = {
    ['water'] = 0.5,
    ['coffee'] = 0.5,
    ['kurkakola'] = 0.5,
    ['tosti'] = 0.5,
    ['twerks_candy'] = 0.5,
    ['snikkel_candy'] = 1,
    ['sandwich'] = 0.5,
    ['hotdog'] = 0.5,
    ['energy_drink'] = 0.5,
    ['beer_pib'] = 0.5,
    ['beer_log'] = 0.5,
    ['beer_am'] = 0.5,
    ['beer_bar'] = 0.5,
    ['beer_stz'] = 0.5,
    ['liquor_vodka'] = 2,
    ['liquor_whiskey'] = 2,
    ['liquor_rum'] = 2,
    ['liquor_tequila'] = 2,
    ['phone'] = 7,
    ['radio'] = 7,
    ['laptop'] = 7,
    ['boombox'] = 7,
    ['race_dongle'] = 14,
    ['trowel'] = 1,
    ['weapon_snspistol_mk2'] = 7,
    ['weapon_vintagepistol'] = 7,
    ['weapon_pistol_mk2'] = 7,
    ['weapon_heavypistol'] = 7,
    ['weapon_pistol50'] = 7,

    ['jobfood'] = 2,
    -- ['phone'] = 20,
    -- ['radio'] = 10,
    -- ['laptop'] = 20,
    -- ['race_dongle'] = 15,
}

Config.weaponclip = {
    ['pistol_clip'] = true,
    ['smg_clip'] = true,
    ['rifle_clip'] =true,
}
Config.Objects = {
	['radio'] = 'prop_cs_hand_radio',
    ['pdradio'] = 'prop_cs_hand_radio',
    ['radiojammer'] = 'h4_prop_h4_jammer_01a',
	['phone'] = 'scrlt_ifruit14max_01',
    ['backpack'] = 'vw_prop_vw_backpack_01a',
    ['lockpick'] = 'bzzz_props_lockpick_04',
    ['hack_laptop'] = 'm23_1_prop_m31_laptop_01a',
    ['zat-notebook'] = 'v_med_p_notebook',
    ['c4_bomb'] = 'prop_explosive_c4',
    ['blueprint'] = 'm23_2_prop_m32_blueprt_01a',
    --weapon clip
    ['pistol_clip'] = 'w_pi_sns_pistol_mag1',
    ['smg_clip'] = 'w_sb_smg_mag1',
    ['rifle_clip'] = 'w_ar_carbinerifle_mag1',
    ['policebadge'] = 'm23_2_prop_m32_police_badge_01a',
    --food and drink
    ['water'] = 'prop_ld_flow_bottle',
    ['energy_drink'] = 'prop_energy_drink',
    ['hotdog'] = 'prop_cs_hotdog_01',
    ['beer_pib'] = 'prop_beer_pissh',
    ['beer_log'] = 'prop_beer_logger',
    ['beer_am'] = 'prop_beer_am',
    ['beer_bar'] = 'prop_beer_bar',
    ['beer_stz'] = 'prop_beer_stz',
    ['liquor_vodka'] = 'prop_vodka_bottle',
    ['liquor_whiskey'] = 'prop_whiskey_bottle',
    ['liquor_rum'] = 'prop_rum_bottle',
    ['liquor_tequila'] = 'prop_tequila_bottle',
    ['cigarette_pack'] = 'prop_cigar_pack_01',
    ['cigarette'] = 'ng_proc_cigarette01a',
    ['cigar'] = 'prop_cigar_02',
    ['zatfoodcontainer'] = 'prop_food_cb_bag_01',
    ['zatburger'] = 'prop_cs_burger_01',
    ['zatsprunk'] = 'ng_proc_sodacup_01a',
    ['zatecola'] = 'ng_proc_sodacup_01a',
    ['zatecolalight'] = 'ng_proc_sodacup_01a',
    ['zatorangotang'] = 'ng_proc_sodacup_01a',
    --houserobbery items

    ['weapon_pumpshotgun'] = 'w_sg_pumpshotgun',
    ['weapon_bat'] = 'p_cs_bbbat_01',
    ['weapon_bottle'] = 'w_me_bottle',
    ['weapon_crowbar'] = 'w_me_crowbar',
    ['weapon_flashlight'] = 'prop_tool_hammer',
    ['weapon_hatchet'] = 'w_me_hatchet',
    ['weapon_knuckle'] = 'w_me_knuckle_slg',
    ['weapon_knife'] = 'prop_w_me_knife_01',
    ['weapon_machete'] = 'ch_prop_ch_bloodymachete_01a',
    ['weapon_switchblade'] = 'w_me_switchblade',
    ['weapon_nightstick'] = 'w_me_nightstick',
    ['weapon_wrench'] = 'prop_tool_wrench',
    ['weapon_battleaxe'] = 'w_me_battleaxe',
    ['weapon_poolcue'] = 'w_me_poolcue',
    ['weapon_stone_hatchet'] = 'w_me_stonehatchet',
    ['weapon_pistol'] = 'w_pi_pistol',
    ['weapon_pistol_mk2'] = 'w_pi_pistol',
    ['weapon_combatpistol'] = 'w_pi_pistol',
    ['weapon_appistol'] = 'w_pi_pistol',
    ['weapon_pistol50'] = 'w_pi_pistol50',
    ['weapon_snspistol'] = 'w_pi_sns_pistol',
    ['weapon_snspistol_mk2'] = 'w_pi_sns_pistolmk2',
    ['weapon_heavypistol'] = 'w_pi_heavypistol',
    ['weapon_vintagepistol'] = 'w_pi_vintage_pistol',
    ['weapon_flaregun'] = 'w_pi_flaregun',
    ['weapon_revolver'] = 'w_pi_revolver',
    ['weapon_revolver_mk2'] = 'w_pi_revolver',
    ['weapon_doubleaction'] = 'w_pi_revolver',
    ['weapon_navyrevolver'] = 'w_pi_revolver',
    ['weapon_stungun'] = 'w_pi_stungun',
    ['weapon_microsmg'] = 'w_sb_microsmg',
    ['weapon_smg'] = 'w_sb_smg',
    ['weapon_smg_mk2'] = 'w_sb_smgmk2',
    ['weapon_assaultsmg'] = 'w_sb_assaultsmg',
    ['weapon_combatpdw'] = 'w_sb_pdw',
    ['weapon_machinepistol'] = 'w_sb_compactsmg',
    ['weapon_minismg'] = 'w_sb_minismg',
    ['weapon_assaultrifle'] = 'w_ar_assaultrifle',
    ['weapon_assaultrifle_mk2'] = 'w_ar_assaultriflemk2',
    ['weapon_carbinerifle'] = 'w_ar_carbinerifle',
    ['weapon_carbinerifle_mk2'] = 'w_ar_carbineriflemk2',
    ['weapon_advancedrifle'] = 'w_ar_advancedrifle',
    ['weapon_specialcarbine'] = 'w_ar_specialcarbine',
    ['weapon_specialcarbine_mk2'] = 'w_ar_specialcarbinemk2',
    ['weapon_bullpuprifle'] = 'w_ar_bullpuprifle',
    ['weapon_bullpuprifle_mk2'] = 'w_ar_bullpupriflemk2',
    ['weapon_compactrifle'] = 'w_ar_assaultrifle_smg',
    ['weapon_heavyrifle'] = 'w_ar_heavyrifleh',
    ['weapon_tacticalrifle'] = 'w_ar_carbinerifle_reh',
    ['weapon_sniperrifle'] = 'w_sr_sniperrifle',
    ['weapon_heavysniper'] = 'w_sr_heavysniper',
    ['weapon_molotov'] = 'w_ex_molotov',
    ['weapon_grenade'] = 'w_ex_grenadefrag',
    ['weapon_stickybomb'] = 'prop_bomb_01_s',
    ['weapon_flare'] = 'w_am_flare',
    ['weapon_smokegrenade'] = 'w_ex_grenadesmoke',
    ['weapon_ball'] = 'w_am_baseball',
  
    ['cash'] = 'prop_anim_cash_pile_01',
    ['rolled_cash'] = 'sf_prop_sf_cash_roll_01a',
    ['washedmoney'] = 'prop_anim_cash_pile_02',
    ['banded_cash'] = 'prop_anim_cash_pile_02',

    ['vehiclebattery']='bkr_prop_meth_lithium',
}

Config.ThrowAllow = {
	['radio'] = true,
	['phone'] = true,
    ['backpack'] = true,
    ['weapon_pumpshotgun'] =true,
    ['weapon_bat'] = true,
    ['weapon_bottle'] = true,
    ['weapon_crowbar'] =true,
    ['weapon_flashlight'] = true,
    ['weapon_hatchet'] =true,
    ['weapon_knuckle'] = true,
    ['weapon_knife'] =true,
    ['weapon_machete'] = true,
    ['weapon_switchblade'] =true,
    ['weapon_nightstick'] = true,
    ['weapon_wrench'] = true,
    ['weapon_battleaxe'] =true,
    ['weapon_poolcue'] = true,
    ['weapon_stone_hatchet'] =true,
    ['weapon_pistol'] =true,
    ['weapon_pistol_mk2'] =true,
    ['weapon_combatpistol'] = true,
    ['weapon_appistol'] =true,
    ['weapon_pistol50'] =true,
    ['weapon_snspistol'] = true,
    ['weapon_snspistol_mk2'] =true,
    ['weapon_heavypistol'] =true,
    ['weapon_vintagepistol'] = true,
    ['weapon_flaregun'] = true,
    ['weapon_revolver'] =true,
    ['weapon_revolver_mk2'] = true,
    ['weapon_doubleaction'] =true,
    ['weapon_navyrevolver'] =true,
    ['weapon_stungun'] =true,
    ['weapon_microsmg'] =true,
    ['weapon_smg'] = true,
    ['weapon_smg_mk2'] =true,
    ['weapon_assaultsmg'] = true,
    ['weapon_combatpdw'] = true,
    ['weapon_machinepistol'] =true,
    ['weapon_minismg'] =true,
    ['weapon_assaultrifle'] = true,
    ['weapon_assaultrifle_mk2'] = true,
    ['weapon_carbinerifle'] = true,
    ['weapon_carbinerifle_mk2'] =true,
    ['weapon_advancedrifle'] =true,
    ['weapon_specialcarbine'] = true,
    ['weapon_specialcarbine_mk2'] =true,
    ['weapon_bullpuprifle'] =true,
    ['weapon_bullpuprifle_mk2'] =true,
    ['weapon_compactrifle'] = true,
    ['weapon_heavyrifle'] =true,
    ['weapon_tacticalrifle'] = true,
    ['weapon_sniperrifle'] =true,
    ['weapon_heavysniper'] =true,
    ['weapon_molotov'] = true,
    ['weapon_grenade'] =true,
    ['weapon_stickybomb'] =true,
    ['weapon_flare'] = true,
    ['weapon_smokegrenade'] = true,
    ['weapon_ball'] =true,

    ['cash'] = true,
    ['rolled_cash'] = true,
    ['washedmoney'] =true,
    ['banded_cash'] =true,
}

Config.BackPackClothes = {
    [GetHashKey("mp_m_freemode_01")] = {
        default = 45,
        allow = {
            [40] = true,
            [41] = true,
            [44] = true,
            [45] = true,
            [81] = true,
            [82] = true,
            [85] = true,
            [86] = true,
            [111] = true,
            [112] = true,
            [113] = true,
            [119] = true,
            [120] = true,
            [121] = true,
        }
    },
    [GetHashKey("mp_f_freemode_01")] = {
        default = 45,
        allow = {
            [40] = true,
            [41] = true,
            [44] = true,
            [45] = true,
            [81] = true,
            [82] = true,
            [85] = true,
            [86] = true,
            [111] = true,
        }
    }
}

Config.CustomTrunk = {
    [GetHashKey('taxirooster')] = {maxweight = 0, slots = 0},
    [GetHashKey('dilettante3')] = {maxweight = 0, slots = 0},
    [GetHashKey('boxville7')] = {maxweight = 2000000, slots = 100},
    [GetHashKey('f150')] = {maxweight = 300000, slots = 50},
}

Config.VehiclesTrunk = {
    [0] = {maxweight = 128000, slots = 30},
    [1] = {maxweight = 150000, slots = 40},
    [2] = {maxweight = 175000, slots = 50},
    [3] = {maxweight = 138000, slots = 35},
    [4] = {maxweight = 128000, slots = 30},
    [5] = {maxweight = 130000, slots = 25},
    [6] = {maxweight = 130000, slots = 25},
    [7] = {maxweight = 138000, slots = 25},
    [8] = {maxweight = 5000, slots = 5},
    [9] = {maxweight = 160000, slots = 35},
    [10] = {maxweight = 180000, slots = 35},
    [11] = {maxweight = 180000, slots = 35},
    [12] = {maxweight = 180000, slots = 35},
    [14] = {maxweight = 220000, slots = 50},
    [15] = {maxweight = 220000, slots = 50},
    [17] = {maxweight = 180000, slots = 50},
    [18] = {maxweight = 180000, slots = 50},
    [19] = {maxweight = 200000, slots = 50},
}

Config.customtrunckdoor = {
    [`burrito`] ={doorid=3,bones="door_pside_r"},
    [`speedo`] ={doorid=3,bones="door_pside_r"},
    [`paradise`] ={doorid=3,bones="door_pside_r"},
    [`pony2`] ={doorid=3,bones="door_pside_r"},
    [`speedo5`] ={doorid=3,bones="door_pside_r"},
    [`speedo4`] ={doorid=3,bones="door_pside_r"},
    [`speedo2`] ={doorid=3,bones="door_pside_r"},
    [`stockade`] ={doorid=3,bones="door_pside_r"},
    [`riot`] ={doorid=3,bones="door_pside_r"},
    [`riot 2`] ={doorid=3,bones="door_pside_r"},
    
}
Config.BackEngineVehicles = {
    [`ninef`] = true,
    [`adder`] = true,
    [`vagner`] = true,
    [`t20`] = true,
    [`infernus`] = true,
    [`zentorno`] = true,
    [`reaper`] = true,
    [`comet2`] = true,
    [`comet3`] = true,
    [`jester`] = true,
    [`jester2`] = true,
    [`cheetah`] = true,
    [`cheetah2`] = true,
    [`prototipo`] = true,
    [`turismor`] = true,
    [`pfister811`] = true,
    [`ardent`] = true,
    [`nero`] = true,
    [`nero2`] = true,
    [`tempesta`] = true,
    [`vacca`] = true,
    [`bullet`] = true,
    [`osiris`] = true,
    [`entityxf`] = true,
    [`turismo2`] = true,
    [`fmj`] = true,
    [`re7b`] = true,
    [`tyrus`] = true,
    [`italigtb`] = true,
    [`penetrator`] = true,
    [`monroe`] = true,
    [`ninef2`] = true,
    [`stingergt`] = true,
    [`surfer`] = true,
    [`surfer2`] = true,
    [`gp1`] = true,
    [`autarch`] = true,
    [`tyrant`] = true
}


Config.CustomGlovebox = {
    [GetHashKey('f150')] = {maxweight = 50000, slots = 30},
}

Config.VehiclesGlovebox = {
    [0] = {maxweight = 40000, slots = 10},
    [1] = {maxweight = 45000, slots = 20},
    [2] = {maxweight = 50000, slots = 25},
    [3] = {maxweight = 45000, slots = 20},
    [4] = {maxweight = 40000, slots = 10},
    [5] = {maxweight = 38000, slots = 8},
    [6] = {maxweight = 38000, slots = 8},
    [7] = {maxweight = 38000, slots = 8},
    [9] = {maxweight = 40000, slots = 20},
    [10] = {maxweight = 50000, slots = 25},
    [11] = {maxweight = 50000, slots = 25},
    [12] = {maxweight = 150000, slots = 40},
    [14] = {maxweight = 100000, slots = 30},
    [15] = {maxweight = 100000, slots = 30},
    [16] = {maxweight = 100000, slots = 30},
    [17] = {maxweight = 50000, slots = 25},
    [18] = {maxweight = 50000, slots = 25},
    [19] = {maxweight = 70000, slots = 25},
}

Config.MaximumAmmoValues = {
    ["pistol"] = 250,
    ["smg"] = 250,
    ["shotgun"] = 200,
    ["rifle"] = 250,
}